revolute joint constraints
edrumwri/revolute-joint-parameter-estimation pull request #3
Opened 2018-12-12 02:15 UTC by rleontie

unit test to be added later after this pull

2018-12-12 05:55 UTC, edrumwri requested changes
You haven't introduced tests for any of this code.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-:-LTVyN3h1QJUdfsNgWhs:bi2m6l2)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVyRyN6eH18wTfti5z:-LTVyRyN6eH18wTfti6-:b-7ufovx) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L1)):*
> ```objc
> function cross = computeRevoluteJointConstraints(ui, uj, quat)
> ```

Why do you want to separate the revolute and spherical joint constraints like this? Also, this isn't *really* the revolute joint constraints b/c it's missing the spherical joint constraints.
___
*[computeRevoluteJointConstraints.m, line 9 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVybkpC39U1iENuWEU:-LTVybkpC39U1iENuWEV:b3vs2us) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L9)):*
> ```objc
>    wRi = quat2R(quat);
>    wRj = eye(3); % the 2 body (j) is attached to the world
>    cross = (wRi*ui)' * (wRj*uj);
> ```

A cross product returns a three dimensional vector. That plus the three spherical joint constraints would bring you to six, which would fully constrain the bodies together. That's not right.

I think you need to read Shabana again for the right constraint equations.


<!-- Sent from Reviewable.io -->

2018-12-12 14:21 UTC, rleontie commented
___
*[computeRevoluteJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVyRyN6eH18wTfti5z:-LTXmRzq3_-5NHqLHMMp:b-awjz0y) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why do you want to separate the revolute and spherical joint constraints like this? Also, this isn't *really* the revolute joint constraints b/c it's missing the spherical joint constraints.
</blockquote></details>

the idea here is that this would allow me to simulate the spherical joint without writing the same code again in a different function, are you saying that it would be more explicit and clear to read to combine both?


<!-- Sent from Reviewable.io -->

2018-12-12 15:03 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVyRyN6eH18wTfti5z:-LTXv5hJAha_PPK4FFgA:b-95utib) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L1)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

the idea here is that this would allow me to simulate the spherical joint without writing the same code again in a different function, are you saying that it would be more explicit and clear to read to combine both?
</blockquote></details>

You could keep the individual functions but the revolute constraints should incorporate the spherical ones too.
___
*[computeSphericalJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvWsWDIcsWQaqnpjH:-LTXvWsX4nxFMKVN7WuV:b-9xew5s) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L1)):*
> ```objc
> function RevConstr = computeSphericalJointConstraints(u, y)
> ```

What are u and y? Their names are such that you won't remember what they stand for if you didn't look at this code for a couple of weeks.
___
*[computeSphericalJointConstraints.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvQ2Q70Be783E_4Kf:-LTXvQ2Q70Be783E_4Kg:b-tucwuh) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L3)):*
> ```objc
> function RevConstr = computeSphericalJointConstraints(u, y)
> % computeSphericalJointConstraints(u, y) computes the spherical joint
> % constraints
> ```

This is a good place to describe exactly the equations you are computing.
___
*[computeSphericalJointConstraints.m, line 5 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvJQ5Ao0cxDfMldJS:-LTXvJQ5Ao0cxDfMldJT:bsrta4e) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L5)):*
> ```objc
> % constraints
> 
>     x = y(1:3); %position components
> ```

Spacing after % comment
___
*[computeSphericalJointConstraints.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvfAT7bSPLtlU3bJX:-LTXvfAT7bSPLtlU3bJY:b7i5v60) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L7)):*
> ```objc
>     x = y(1:3); %position components
>     quat = y(4:7); %quaternion components
>     wRi = quat2R(quat);
> ```

How did you pick the variable name for wRi? It's not clear to me why you named it this way.
___
*[computeSphericalJointConstraints.m, line 8 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvtcx1hWQ0_6HxlS6:-LTXvtcy1muspxrytmi_:b9d7ozo) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L8)):*
> ```objc
>     quat = y(4:7); %quaternion components
>     wRi = quat2R(quat);
>     RevConstr = x + wRi * u;
> ```

If you use good frame naming notation in your variables, it should be clear that multiplying the offset vector by the rotation matrix is allowed. You're trusting yourself too much to have performed the right calculation.


<!-- Sent from Reviewable.io -->

2018-12-12 15:05 UTC, rleontie commented
___
*[computeRevoluteJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVyRyN6eH18wTfti5z:-LTXwot_5uSoPrUE0Epg:baw79ee) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You could keep the individual functions but the revolute constraints should incorporate the spherical ones too.
</blockquote></details>

I agree. Working on the changes right now


<!-- Sent from Reviewable.io -->

2018-12-12 17:50 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVyRyN6eH18wTfti5z:-LTYTJauD1mZx-itCAED:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L1)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I agree. Working on the changes right now
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 9 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTVybkpC39U1iENuWEU:-LTYTJER1QYtpcyva6pP:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeRevoluteJointConstraints.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

A cross product returns a three dimensional vector. That plus the three spherical joint constraints would bring you to six, which would fully constrain the bodies together. That's not right.

I think you need to read Shabana again for the right constraint equations.
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvWsWDIcsWQaqnpjH:-LTYX-Cn279FFZl3tJHw:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What are u and y? Their names are such that you won't remember what they stand for if you didn't look at this code for a couple of weeks.
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvQ2Q70Be783E_4Kf:-LTYX-YX-qQ2-4FpdFft:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This is a good place to describe exactly the equations you are computing.
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 5 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvJQ5Ao0cxDfMldJS:-LTYX0oO7NvjQ4M4vTwc:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Spacing after % comment
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvfAT7bSPLtlU3bJX:-LTYX9IA2HtnGMKRRWT9:b-rlgexo) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

How did you pick the variable name for wRi? It's not clear to me why you named it this way.
</blockquote></details>

converts to the world frame
___
*[computeSphericalJointConstraints.m, line 8 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTXvtcx1hWQ0_6HxlS6:-LTYVVQACrkHj5FZJ4H2:bml54ig) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/770c3a8268204e737e942f9ed4f309bcdebe0333/computeSphericalJointConstraints.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

If you use good frame naming notation in your variables, it should be clear that multiplying the offset vector by the rotation matrix is allowed. You're trusting yourself too much to have performed the right calculation.
</blockquote></details>

Could you provide a suggestion here, please?


<!-- Sent from Reviewable.io -->

2018-12-12 17:51 UTC, rleontie commented
After we settle on the two functions I will add unit testing





<!-- Sent from Reviewable.io -->

2018-12-12 19:36 UTC, edrumwri requested changes
Suggestion: look over your code before hitting "Publish" (multiple commits are fine) so that you're not continually getting dinged on the same kinds of problems repeatedly.

> Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-:-LTYuc8t73wzxwoJInQO:b-he7ocb)* status: 2 of 6 files reviewed, 14 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[compute2OrtogonalVect.m, line 2 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYYYdn49KQ8TR4lw_m:-LTYYYdo3hGstsEbfKPx:b-evzx11) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/compute2OrtogonalVect.m#L2)):*
> ```objc
> function [v1i,v2i] = compute2OrtogonalVect(vi)
> % compute2OrtogonalVect(vi) for a given nonzero column vector (3,1) vi compute
> ```

You've misspelled "orthogonal" :(

We argued over the name in Drake extensively for the same functionality. We called it ComputeBasisFromAxis(.).
___
*[compute2OrtogonalVect.m, line 14 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYsoEY4275VIMLJfUw:-LTYsoEY4275VIMLJfUx:bdipeso) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/compute2OrtogonalVect.m#L14)):*
> ```objc
>     vd(i) = 0;
>     v1i = cross(vi, vd);
>     v2i = cross(vi, v1i);
> ```

This method will fail if vi is a zero vector.
___
*[computeRevoluteJointConstraints.m, line 2 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtTR-E85wg4Y-5MBE:-LTYtTR-E85wg4Y-5MBF:b-5qow1v) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L2)):*
> ```objc
> function revoluteConstraints = computeRevoluteJointConstraints(ui, vi, vj,  pose)
> % computeRevoluteJointConstraints(ui, uj, quat) computes the revolute joint 
> ```

This documentation does not match your function signature.
___
*[computeRevoluteJointConstraints.m, line 4 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtPe71aqGkh7XqDw_:-LTYtPe82YQ4HvmFX4ZO:b-4ehi1k) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L4)):*
> ```objc
> % computeRevoluteJointConstraints(ui, uj, quat) computes the revolute joint 
> % constraints as spherical joint constraints with two aditional constraints.
> %   ui is a 3x1 local position vector (on body i) defining the joint
> ```

Any preconditions on ui?
___
*[computeRevoluteJointConstraints.m, line 6 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtIcP7xB1Byjp_MvE:-LTYtIcP7xB1Byjp_MvF:b-jx7woz) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L6)):*
> ```objc
> %   ui is a 3x1 local position vector (on body i) defining the joint
> %   location wrt the grasping point.
> %   vi is a 3x1 vector for the revolute joint in the body i frame.
> ```

What are the preconditions (if any) for vi and vj?
___
*[computeRevoluteJointConstraints.m, line 8 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYt_j9DD4TR9EKDCHF:-LTYt_j9DD4TR9EKDCHG:b4zi12i) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L8)):*
> ```objc
> %   vi is a 3x1 vector for the revolute joint in the body i frame.
> %   vj is a 3x1 vector for the revolute joint in the body j frame (fixed to the world).
> %   y is a7x1 vector representing the position and orientation of the 
> ```

FYI typo: "a7x1"
___
*[computeRevoluteJointConstraints.m, line 8 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtcsH5ldgH0DmkgJb:-LTYtcsI1VMc2c9xKJ2j:b-ymllnr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L8)):*
> ```objc
> %   vi is a 3x1 vector for the revolute joint in the body i frame.
> %   vj is a 3x1 vector for the revolute joint in the body j frame (fixed to the world).
> %   y is a7x1 vector representing the position and orientation of the 
> ```

How are position and orientation represented in y?
___
*[computeRevoluteJointConstraints.m, line 9 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYthqZBatQokixn_D_:-LTYthqZBatQokixn_Da:b-gm41i0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L9)):*
> ```objc
> %   vj is a 3x1 vector for the revolute joint in the body j frame (fixed to the world).
> %   y is a7x1 vector representing the position and orientation of the 
> %   grasping point in the global frame.
> ```

I don't think there should be any notion of a grasping point in this code- it's just not relevant.
___
*[computeRevoluteJointConstraints.m, line 14 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtXtGBffXD-kBGi06:-LTYtXtGBffXD-kBGi07:b-bwqwnz) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L14)):*
> ```objc
>     quat = pose(4:7); % quaternion components
>     wRi = quat2R(quat);
>     wRj = eye(3); % the 2 body (j) is attached to the world
> ```

What does this mean: "the 2 body"?
___
*[computeRevoluteJointConstraints.m, line 20 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtoM08-Lxi8bLOzVr:-LTYtoM08-Lxi8bLOzVs:b8ig4z7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L20)):*
> ```objc
>     vjw = wRj * vj; 
>     
>     % Formulate the parallelism condition of the two vectors wvi and wvj as
> ```

Comment doesn't match the code.
___
*[computeRevoluteJointConstraints.m, line 22 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYts_5AG6APRvjsd_j:-LTYts_5AG6APRvjsd_k:bc71lok) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L22)):*
> ```objc
>     % Formulate the parallelism condition of the two vectors wvi and wvj as
>     % two independent dot product equations.
>     [v1iw, v2iw] = compute2OrtogonalVect(viw);
> ```

Does it make any difference whether these vectors are computed on the fly or computed once and then passed into this function?
___
*[computeRevoluteJointConstraints.m, line 25 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYu4u26z_MI015LFNs:-LTYu4u26z_MI015LFNt:b-o0mhlw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L25)):*
> ```objc
>     revolute_parallel_vect = [v1iw' * vjw; v2iw' * vjw];
>     
>     sphericalConstraints = x + wRi * ui;
> ```

Why are you not using the spherical constraint function? Asked another way: why are you duplicating code?
___
*[computeSphericalJointConstraints.m, line 3 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYuFHe1x3AzbsP7c3h:-LTYuFHf2hhhu71FeCuI:b-d43fvy) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeSphericalJointConstraints.m#L3)):*
> ```objc
> function sphericalConstraints = computeSphericalJointConstraints(ui, pose)
> % computeSpherical [...]

2018-12-12 21:42 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: 1 of 6 files reviewed, 14 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 2 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtTR-E85wg4Y-5MBE:-LTZHpEe868_ytdr3Y_p:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L2)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This documentation does not match your function signature.
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 4 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtPe71aqGkh7XqDw_:-LTZHq8H18TqlBT4_Zyg:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Any preconditions on ui?
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 6 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtIcP7xB1Byjp_MvE:-LTZHtGMEt9MBigKCZti:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L6)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What are the preconditions (if any) for vi and vj?
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 8 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtcsH5ldgH0DmkgJb:-LTZHzsg59LxaPdeBO8g:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

How are position and orientation represented in y?
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 9 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYthqZBatQokixn_D_:-LTZI2PAAwNEwh-p93Vl:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't think there should be any notion of a grasping point in this code- it's just not relevant.
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 14 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtXtGBffXD-kBGi06:-LTZMRsl8Ph_r4mYrWuu:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What does this mean: "the 2 body"?
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 20 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtoM08-Lxi8bLOzVr:-LTZMTfH8P-OM8jkzK4L:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Comment doesn't match the code.
</blockquote></details>

Done.
___
*[computeRevoluteJointConstraints.m, line 22 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYts_5AG6APRvjsd_j:-LTZF1Xb4i3-romi8dj6:bnxw40p) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L22)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Does it make any difference whether these vectors are computed on the fly or computed once and then passed into this function?
</blockquote></details>

I see your point. it is more efficient if I calculate them once, but if I pass them as parameters it is not as clear as what are the original 2 vectors 
___
*[computeRevoluteJointConstraints.m, line 25 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYu4u26z_MI015LFNs:-LTZM4LV3GtvKPxyH94y:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L25)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why are you not using the spherical constraint function? Asked another way: why are you duplicating code?
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 3 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYuFHe1x3AzbsP7c3h:-LTZMW2g6tSTjq80tdX5:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeSphericalJointConstraints.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What is f? Also, you should make it clear that the constraints are satisfied when this equation evaluates to zero.
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 6 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYuMy0E2N3Kl56XOjt:-LTZMJU9CirYqSRqhvC8:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeSphericalJointConstraints.m#L6)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Same typo here as above.
</blockquote></details>

Done.
___
*[compute2OrtogonalVect.m, line 2 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYYYdn49KQ8TR4lw_m:-LTZHdXw3N9pPK6zzC58:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/compute2OrtogonalVect.m#L2)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You've misspelled "orthogonal" :(

We argued over the name in Drake extensively for the same functionality. We called it ComputeBasisFromAxis(.).
</blockquote></details>

Done.
___
*[compute2OrtogonalVect.m, line 14 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYsoEY4275VIMLJfUw:-LTZHfWU3C92ENfZ8td3:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/compute2OrtogonalVect.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This method will fail if vi is a zero vector.
</blockquote></details>

Done.
___
*[Testcompute2OrtogonalVect.m, line 15 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYuYEuBc0ST5Z5F2BJ:-LTZH0dk6uc_I66YTA4w:bs5oa4k) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/Testcompute2OrtogonalVect.m#L15)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Generally you want these vectors to be normalized.
</blockquote></details>

I agree but is not a condition of this function, it is a condition of other functions that use it. This is an example from Shabana.


<!-- Sent f [...]

2018-12-12 21:52 UTC, edrumwri requested changes
> Reviewed 1 of 4 files at r4, 3 of 4 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: all files reviewed, 11 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJointConstraints.m, line 20 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtoM08-Lxi8bLOzVr:-LTZNjW9-QytKZFYL40h:bfhqmln) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L20)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[computeRevoluteJointConstraints.m, line 22 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYts_5AG6APRvjsd_j:-LTZNskXCPEv5aTg4F49:bc8ffn7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L22)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I see your point. it is more efficient if I calculate them once, but if I pass them as parameters it is not as clear as what are the original 2 vectors 
</blockquote></details>

I just wanted to check your understanding. The code is indeed fine as-is.
___
*[computeSphericalJointConstraints.m, line 5 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZO2HY2ah6zaPBc9Qt:-LTZO2HY2ah6zaPBc9Qu:br1cd1u) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeSphericalJointConstraints.m#L5)):*
> ```objc
> % constraints defined as x + R * u = 0.
> %   ui is a 3x1 local position vector (on body i) defining the joint
> %   location wrt the grasping point.
> ```

Nit You're talking about a grasping point here again.
___
*[computeSphericalJointConstraints.m, line 8 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOIA7422-XQlU7A5w:-LTZOIA7422-XQlU7A5x:b-c31adw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeSphericalJointConstraints.m#L8)):*
> ```objc
> %   pose is a 7x1 vector representing the:
> %       position: values 1:3 in pose in the format x y z and
> %       orientation: values 4:7 in pose in a quaternion format w x y z
> ```

You use x y and z here and above for different purposes. I'd call these ew, ex, ey, ez or qw, qx, qy, qz.
___
*[computeSphericalJointConstraints.m, line 10 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZO9_w813JYFfCu665:-LTZO9_w813JYFfCu666:b-hpmn3y) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeSphericalJointConstraints.m#L10)):*
> ```objc
> %       orientation: values 4:7 in pose in a quaternion format w x y z
> 
>     x = pose(1:3); % position components
> ```

Now you're using "x" in two contexts: here as a 3-dimensional vector and in your comment directly above as a scalar.
___
*[TestcomputeSphericalJointConstraints.m, line 9 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOxOFDrsbr5xmPKSD:-LTZOxOFDrsbr5xmPKSE:b1lqujy) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeSphericalJointConstraints.m#L9)):*
> ```objc
>     methods (Test)   
>         function testComputationIdentity(testCase)
>             % testComputationIdentity no rotation just addition of two vectors.
> ```

I'm not sure what you mean by "just addition of two vectors".
___
*[TestcomputeSphericalJointConstraints.m, line 13 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZP-zvAUib9mxfrzgq:-LTZP-zwAajMWpeHDTlr:b-tj302b) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeSphericalJointConstraints.m#L13)):*
> ```objc
>             pose = [1 0 0 1 0 0 0]';
>             actSol = computeSphericalJointConstraints(ui, pose);
>             expSol = pose(1:3)+ eye(3) * ui;
> ```

Nit space between ) and +
___
*[computeBasisFromAxis.m, line 8 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZN7p_Db6BIKPgXj-D:-LTZN7pa0aVMmiMU2Iyp:b-bnz8sw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeBasisFromAxis.m#L8)):*
> ```objc
> %   these vectors are computed.
> 
>     if any(v(:) == 0), error(message('the vector should not be all zeros')); end
> ```

Doesn't this detect whether *any* of the elements are zero, rather than the entire vector being zero?
___
*[TestcomputeBasisFromAxis.m, line 4 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOR-ECTmzLPXpC9Va:-LTZOR-ECTmzLPXpC9Vb:bu8u0k6) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeBasisFromAxis.m#L4)):*
> ```objc
>     % TestcomputeBasisFromAxis performs unit testing for computeBasisFromAxis.
>     %   testComputation tests the computation against a know solution.
>     %   testOrtogonal tests if the 3 vectors form an ortogonal triad.
> ```

Same mispelling as before.
___
*[TestcomputeBasisFromAxis.m, line 9 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOj5V2dImsUpSUnsb:-LTZOj5V2dImsUpSUnsc:b-xa9s36) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeBasisFromAxis.m#L9)):*
> ```objc
>     end
> 
>     methods (Test)   
> ```

You test for an error condition in the code: that the zero vector throws an error. You want to test verify that happens.
___
*[TestcomputeBasisFromAxis.m, line 11 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOZCN4bE1Q51s6SQ3:-LTZOZCN4bE1Q51s6SQ4:b-mimip2) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeBasisFromAxis.m#L11)):*
> ```objc
>     methods (Test)   
>         function testComputation(testCase)
>             % testComputation tests against a know solution. 
> ```

Typo: know


<!-- Sent from Reviewable.io -->

2018-12-12 22:33 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 22 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYts_5AG6APRvjsd_j:-LTZRaeB5h0LRYYFXYnZ:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L22)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I just wanted to check your understanding. The code is indeed fine as-is.
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 8 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOIA7422-XQlU7A5w:-LTZY8ocDPEQcY3j73BN:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeSphericalJointConstraints.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You use x y and z here and above for different purposes. I'd call these ew, ex, ey, ez or qw, qx, qy, qz.
</blockquote></details>

Done.
___
*[computeSphericalJointConstraints.m, line 10 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZO9_w813JYFfCu665:-LTZY9rz2uOGo3VkvkYf:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeSphericalJointConstraints.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Now you're using "x" in two contexts: here as a 3-dimensional vector and in your comment directly above as a scalar.
</blockquote></details>

Done.
___
*[TestcomputeSphericalJointConstraints.m, line 9 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOxOFDrsbr5xmPKSD:-LTZYPco7LuUsnuhSMPD:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeSphericalJointConstraints.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'm not sure what you mean by "just addition of two vectors".
</blockquote></details>

Done.
___
*[computeBasisFromAxis.m, line 8 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZN7p_Db6BIKPgXj-D:-LTZW_Jy-kSzTp08wW8B:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeBasisFromAxis.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Doesn't this detect whether *any* of the elements are zero, rather than the entire vector being zero?
</blockquote></details>

Done.
___
*[TestcomputeBasisFromAxis.m, line 4 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOR-ECTmzLPXpC9Va:-LTZYVgwAhjXUKd9yuPo:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeBasisFromAxis.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Same mispelling as before.
</blockquote></details>

Done.
___
*[TestcomputeBasisFromAxis.m, line 9 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOj5V2dImsUpSUnsb:-LTZYHxpDffk_d0jS2mN:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeBasisFromAxis.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You test for an error condition in the code: that the zero vector throws an error. You want to test verify that happens.
</blockquote></details>

Done.
___
*[TestcomputeBasisFromAxis.m, line 11 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZOZCN4bE1Q51s6SQ3:-LTZYJQ-3E7RS3v61VR-:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/TestcomputeBasisFromAxis.m#L11)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Typo: know
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-12 23:02 UTC, edrumwri requested changes
Looking pretty good- almost there.

> Reviewed 1 of 3 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-:-LTZdz834lmaC5NsdA5J:b52o938)* status: all files reviewed, 4 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 5 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZbQqX5kNSTBZ02O_L:-LTZbQqX5kNSTBZ02O_M:b-sqepqk) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/1e488564e984df599e2a4e4008768533caea668c/computeRevoluteJointConstraints.m#L5)):*
> ```objc
> % constraints as spherical joint constraints with two additional constraints.
> % The two additional constraints are for vector vi and vj to be parallel. 
> %   ui is a 3x1 unit vector representing local position vector on body i 
> ```

Nit ui need not be a unit vector.
___
*[computeSphericalJointConstraints.m, line 4 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZacdo7OzsoWJJg8N5:-LTZacdo7OzsoWJJg8N6:b-nhol37) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/1e488564e984df599e2a4e4008768533caea668c/computeSphericalJointConstraints.m#L4)):*
> ```objc
> % computeSphericalJointConstraints(ui, pose) computes the spherical joint
> % constraints defined as x + R * u = 0.
> %   ui is a 3x1 unit vector representing local position vector on body i
> ```

Nit ui should not be a unit vector
___
*[computeBasisFromAxis.m, line 8 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZN7p_Db6BIKPgXj-D:-LTZb76I2b7TQsfMCjkE:b-i68wz0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeBasisFromAxis.m#L8)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought this was still wrong, but your unit tests have me convinced otherwise!


<!-- Sent from Reviewable.io -->

2018-12-12 23:13 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 20 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtoM08-Lxi8bLOzVr:-LTZQDP45qxmU8GalCJc:b-rjj1n3) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Can you help me here? I am saying vectors wvi and wvj not wv1i etc. between those it is a perpendicular condition right? I wanted to have a more descriptive comment but maybe something more simple will work :)


<!-- Sent from Reviewable.io -->

2018-12-12 23:59 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 20 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtoM08-Lxi8bLOzVr:-LTZqxzM0lJeVFdmuVKi:b-urlahs) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L20)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Can you help me here? I am saying vectors wvi and wvj not wv1i etc. between those it is a perpendicular condition right? I wanted to have a more descriptive comment but maybe something more simple will work :)
</blockquote></details>

You've got vectors wvi and wvj in the comments but the names are viw and vjw.


<!-- Sent from Reviewable.io -->

2018-12-13 00:55 UTC, rleontie reviewed
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: all files reviewed, 2 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 20 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTYtoM08-Lxi8bLOzVr:-LT_2Oot2UhDGZmwrm64:b-896fjx) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/21752da7aba8ed5cdfd32baa057c3610e2d5146b/computeRevoluteJointConstraints.m#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You've got vectors wvi and wvj in the comments but the names are viw and vjw.
</blockquote></details>

Done
___
*[computeBasisFromAxis.m, line 8 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LTZN7p_Db6BIKPgXj-D:-LTZeLgO4Y1RSqm6Txo5:bs7wtrx) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c65e1e01acdceea4e05ea27212e201b4660e25bf/computeBasisFromAxis.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I thought this was still wrong, but your unit tests have me convinced otherwise!
</blockquote></details>

Done
 


<!-- Sent from Reviewable.io -->

2018-12-13 01:04 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: all files reviewed, 2 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeBasisFromAxis.m, line 8 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LT_4n4E2NAbGFc_aPNP:-LT_4n4F6WrqR2WFx35F:b-e52ru1) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c1031c66fe244c12866e6c96a69ace575258151a/computeBasisFromAxis.m#L8)):*
> ```objc
> %   these vectors are computed.
> 
>     if all(vi(:) == 0), error('computeBasisFromAxis:InputIsZeros','The vector should not be all zeros'); end
> ```

Style issue: `if` statements should be formatted like:

    if a
      do stuff
    end


<!-- Sent from Reviewable.io -->

2018-12-13 01:09 UTC, rleontie commented
___
*[computeBasisFromAxis.m, line 8 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LT_4n4E2NAbGFc_aPNP:-LT_5Z094ULIRFfpFIzk:b-d0mmor) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c1031c66fe244c12866e6c96a69ace575258151a/computeBasisFromAxis.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Style issue: `if` statements should be formatted like:

    if a
      do stuff
    end
</blockquote></details>

I really used the convention for this :)  https://sites.google.com/site/matlabstyleguidelines/layout-documentation/layout
I can change it if you prefer that.  


<!-- Sent from Reviewable.io -->

2018-12-13 01:11 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: all files reviewed, 1 unresolved discussion (waiting on @rleontie)

___
*[computeBasisFromAxis.m, line 8 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LT_4n4E2NAbGFc_aPNP:-LT_6Nxd3-URQedYGFKO:b-kuertb) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c1031c66fe244c12866e6c96a69ace575258151a/computeBasisFromAxis.m#L8)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I really used the convention for this :)  https://sites.google.com/site/matlabstyleguidelines/layout-documentation/layout
I can change it if you prefer that.  
</blockquote></details>

Yeah, that's not a short statement though.


<!-- Sent from Reviewable.io -->

2018-12-13 01:13 UTC, rleontie commented
___
*[computeBasisFromAxis.m, line 8 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3#-LT_4n4E2NAbGFc_aPNP:-LT_71ks3YaYkSssKVO5:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/c1031c66fe244c12866e6c96a69ace575258151a/computeBasisFromAxis.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Yeah, that's not a short statement though.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-13 01:13 UTC, edrumwri approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/3)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-13 01:14 UTC, merged