Numerical estimation for the revolute joint jacobian
edrumwri/revolute-joint-parameter-estimation pull request #4
Opened 2018-12-13 02:31 UTC by rleontie

2018-12-13 05:37 UTC, edrumwri requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @rleontie)

___
*[computeN.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_rLj58shCNP7rILyJ:-LT_rLj64FmF2J8avCFR:b546a2s) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeN.m#L3)):*
> ```objc
> function N = computeN(quat)
> % computeN(quat) returns matrix N used in calculation of the jacobian.
> %   quat is a 4 elements vector quaternion in format qw qx qy qz
> ```

nit "elements" -> "element"
___
*[computeNikraveshG.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_rRxs4YWJc768lJ7R:-LT_rRxtCkSsxbuvqnTD:b3yl3dc) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeNikraveshG.m#L7)):*
> ```objc
> %   This is the Euler parameters transformation matrix.  
> %   Based on equation 6.38 from Nikravesh book "Computer-Aided Analysis of
> %   Machanical Systems." (1988)
> ```

Nit misspelling "Machanical" 
___
*[computeNikraveshG.m, line 9 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_rY35Dzx4_p8HSur0:-LT_rY35Dzx4_p8HSur1:bxgpy48) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeNikraveshG.m#L9)):*
> ```objc
> %   Machanical Systems." (1988)
> 
> % e0 = qw component, e1 = qx component, e2 = qy component, e3 = qz component
> ```

You call these qw, etc. above. A comment isn't sufficient to rename. You should either put e0, etc. above or qw, etc. below.
___
*[computeRevoluteJacobianNum.m, line 6 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa2JWX9mtuk5CnSDdK:-LTa2JWX9mtuk5CnSDdL:bcysisn) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L6)):*
> ```objc
> %   Uses the forward-difference formula to calculate the jacobian using 
> %   computeRevoluteJointConstraints function
> %   ui is a 3x1 vector representing local position vector on body i 
> ```

This isn't just "on body i" and this is not a "local position vector". This is a "vector from the center-of-mass" (or other reference point, but be specific) "of body i to the revolute joint location and expressed in the body i frame".
___
*[computeRevoluteJacobianNum.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa2kpNE-ymfjN8RXoE:-LTa2kpNE-ymfjN8RXoF:b7rctet) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L7)):*
> ```objc
> %   computeRevoluteJointConstraints function
> %   ui is a 3x1 vector representing local position vector on body i 
> %   vi is a 3x1 unit vector for the revolute joint in the body i frame.
> ```

This points along the joint axis.
___
*[computeRevoluteJacobianNum.m, line 14 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_zAWj1lpAH5oGgSh1:-LT_zAWj1lpAH5oGgSh2:bqtswxz) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L14)):*
> ```objc
> %   eps is the epsilon used in the forward calculation.
> 
>     % perturbe pose by eps
> ```

sp "perturbe"
___
*[computeRevoluteJacobianNum.m, line 22 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa00NaCpBHQWZW3d_g:-LTa00NaCpBHQWZW3d_h:bkwed9q) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L22)):*
> ```objc
>     f = zeros(5, col);
>     % Precompute the value for the constraints with no perturbance.
>     fi = computeRevoluteJointConstraints(ui, vi, vj, pose);
> ```

I think you need a better variable name than `fi` since it's not apparent to me what it stands for.
___
*[computeRevoluteJacobianNum.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_zf1C3tA0FqdsUzbU:-LT_zf1C3tA0FqdsUzbV:byxl9tk) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L26)):*
> ```objc
>     for i = 1:col
>         % Update the ith component of pose for the estimation.
>         poseForward = pose;
> ```

Wow, this isn't wrong but it is a strange way to do this. We try to do in code what people expect, so I'd recommend changing this to set posePerturbed here to poseForward and then add eps to the ith value of posePerturbed.
___
*[computeRevoluteJacobianNum.m, line 31 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa0d38BqAh-mAYWsLY:-LTa0d38BqAh-mAYWsLZ:bl2pwv7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L31)):*
> ```objc
>         fForward(:, i) = computeRevoluteJointConstraints(ui, vi, vj, poseForward);
>         % Add element to f calculation.
>         f(:, i) = fi;
> ```

You've creating a bunch of rows of the same vector? Ok, the calculation is right, but that's not a great way to do it. If you feel like the abstract you're doing is so powerful, you can replicate fi using repmat. But I don't know why you'd not just do the subtraction right as it's getting placed into fForward?
___
*[computeRevoluteJacobianNum.m, line 38 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa1FOk2-u22FK-l8gh:-LTa1FOk2-u22FK-l8gi:byunxgr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L38)):*
> ```objc
>     N = computeN(quat);
>     
>     JRevNum = (fForward - f)/ eps * N;    
> ```

Not space between ) and /
___
*[computeRevoluteJacobianNum.m, line 38 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa1gVi8yselF44kjCx:-LTa1gVi8yselF44kjCy:brz05d) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L38)):*
> ```objc
>     N = computeN(quat);
>     
>     JRevNum = (fForward - f)/ eps * N;    
> ```

There is a lot going on in this one statement. The biggest thing is that we need to document why we multiply by N. The answer is that we want JRevNum * v = ∂f/∂q * dq/dt to match. But we're given this relationship dq/dt = N*v, so we know that JRevNum * v = ∂f/∂q * N * v. Therefore, we know that JRevNum =  ∂f/∂q * N.
___
*[TestcomputeNikraveshG.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa329F00OGsAOUt6HI:-LTa329F00OGsAOUt6HJ:bsy59ce) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/TestcomputeNikraveshG.m#L26)):*
> ```objc
>             actSol = NG * NG';
>             expSol = eye(3);
>             % Absolute error 4 * sqrt(eps) = 5.9605e-08
> ```

FYI We normally go with as tight of a tolerance we can get away with. If your numbers are all about unit magnitude, then the error from a typical floating point calculation will typically be about 2e-16. One of my colleagues like to relax this only as much as humanly possible (like 1e-16 often). I'm not that extreme- I often use 1e-14. But that's the kind of accuracy that we expect to get with the code that we're writing.


<!-- Sent from Reviewable.io -->

2018-12-13 05:43 UTC, edrumwri reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 11 unresolved discussions (waiting on @rleontie)



<!-- Sent from Reviewable.io -->

2018-12-13 14:54 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @edrumwri)

___
*[computeNikraveshG.m, line 9 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_rY35Dzx4_p8HSur0:-LTbx1XP5crGqEv4VsO4:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeNikraveshG.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You call these qw, etc. above. A comment isn't sufficient to rename. You should either put e0, etc. above or qw, etc. below.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianNum.m, line 6 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa2JWX9mtuk5CnSDdK:-LTc2LJi-azbYM3GO5J0:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L6)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This isn't just "on body i" and this is not a "local position vector". This is a "vector from the center-of-mass" (or other reference point, but be specific) "of body i to the revolute joint location and expressed in the body i frame".
</blockquote></details>

Done.
___
*[computeRevoluteJacobianNum.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa2kpNE-ymfjN8RXoE:-LTc2PiL9B_7rD2TMwte:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This points along the joint axis.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianNum.m, line 14 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_zAWj1lpAH5oGgSh1:-LTc2TjA8fzJ56NBcVWH:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

sp "perturbe"
</blockquote></details>

Done.
___
*[computeRevoluteJacobianNum.m, line 22 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa00NaCpBHQWZW3d_g:-LTc2W6gEp44arJkn5e_:bs7wv0y) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L22)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I think you need a better variable name than `fi` since it's not apparent to me what it stands for.
</blockquote></details>

Done?
___
*[computeRevoluteJacobianNum.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_zf1C3tA0FqdsUzbU:-LTbyg3z7iEo0CBh-f1_:bl0j7vo) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L26)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Wow, this isn't wrong but it is a strange way to do this. We try to do in code what people expect, so I'd recommend changing this to set posePerturbed here to poseForward and then add eps to the ith value of posePerturbed.
</blockquote></details>

this doesn't make sense... I would add 2 * eps if I do that. See this solution:
___
*[computeRevoluteJacobianNum.m, line 31 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa0d38BqAh-mAYWsLY:-LTc-6Xc3ArWGis-ern2:b-aynjfa) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L31)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You've creating a bunch of rows of the same vector? Ok, the calculation is right, but that's not a great way to do it. If you feel like the abstract you're doing is so powerful, you can replicate fi using repmat. But I don't know why you'd not just do the subtraction right as it's getting placed into fForward?
</blockquote></details>

I agree it is not the most efficient way. I am going to do the subtraction at line 38 though for clarity. 
___
*[computeRevoluteJacobianNum.m, line 38 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa1FOk2-u22FK-l8gh:-LTc-L7I6-px-qi0Gv5B:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L38)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Not space between ) and /
</blockquote></details>

Done.
___
*[computeRevoluteJacobianNum.m, line 38 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa1gVi8yselF44kjCx:-LTc0OxE7YFjp9eofS7s:b-896fig) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L38)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

There is a lot going on in this one statement. The biggest thing is that we need to document why we multiply by N. The answer is that we want JRevNum * v = ∂f/∂q * dq/dt to match. But we're given this relationship dq/dt = N*v, so we know that JRevNum * v = ∂f/∂q * N * v. Therefore, we know that JRevNum =  ∂f/∂q * N.
</blockquote></details>

Done?
___
*[TestcomputeNikraveshG.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa329F00OGsAOUt6HI:-LTc0W8q6o89_7rPVbx5:beutevh) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/TestcomputeNikraveshG.m#L26)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI We normally go with as tight of a tolerance we can get away with. If your numbers are all about unit magnitude, then the error from a typical floating point calculation will typically be about 2e-16. One of my colleagues like to relax this only as much as humanly possible (like 1e-16 often). I'm not that extreme- I often use 1e-14. But that's the kind of accuracy that we expect to get with the code that we're writing.
</blockquote></details>

Calculating N I think gives us the accuracy you want but the multiplication introduces error.  Any idea how to address this?


<!-- Sent from Reviewable.io -->

2018-12-13 15:04 UTC, edrumwri requested changes
You should test the numerical Jacobian. The way you can do this is by adding an additional output argument (and necessary input arguments) to the constraint equation evaluations that returns \dot{f}. Then, the numerical Jacobian * v should approximately equal \dot{f}.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-:-LTa1SkJ34An2J0PCWix:bfjr5gp)* status: all files reviewed, 3 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJacobianNum.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_zf1C3tA0FqdsUzbU:-LTc3_Vf-XMW7hNtPGaI:b-f14y30) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L26)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

this doesn't make sense... I would add 2 * eps if I do that. See this solution:
</blockquote></details>

Right- this is what I meant.
___
*[computeRevoluteJacobianNum.m, line 9 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTc3OKy1XP8ixk8brn-:-LTc3OKy1XP8ixk8brn0:b1jpgzy) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/8f9c0a8c17f2bf4913d075716a5e531e6c8fcada/computeRevoluteJacobianNum.m#L9)):*
> ```objc
> %       joint location and expressed in the body i frame 
> %   vi is a 3x1 unit vector that points along the axis of the revolute joint 
> %       in the body i frame.
> ```

nit "in the body" -> "expressed in the body"
___
*[computeRevoluteJacobianNum.m, line 37 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTc4OKP-ayYT1hdGVmt:-LTc4OKQ2mTb19M_9OqV:bgvi6do) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/8f9c0a8c17f2bf4913d075716a5e531e6c8fcada/computeRevoluteJacobianNum.m#L37)):*
> ```objc
>     N = computeN(quat);
>     
>     % JRevNum * v = ?f/?q * dq/dt and dq/dt = N*v, therfore 
> ```

The partials aren't coming through here. I happen to know that partials show up fine in reviewable. Whether they work in MATLAB is a different story... If you can't use the character, a satisfactory replacement is "d".
___
*[TestcomputeNikraveshG.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTa329F00OGsAOUt6HI:-LTc4kqd6jcf2vlGfZlq:bvfb7qi) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/TestcomputeNikraveshG.m#L26)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Calculating N I think gives us the accuracy you want but the multiplication introduces error.  Any idea how to address this?
</blockquote></details>

I'm giving you something to strive for rather than an expectation that you should try to meet this.


<!-- Sent from Reviewable.io -->

2018-12-13 16:15 UTC, rleontie reviewed
Will work on the testing for the numerical Jacobian as you suggested next 

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-:-LTcLQvz1EGotgTzaoSC:b-a06xvi)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJacobianNum.m, line 26 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LT_zf1C3tA0FqdsUzbU:-LTc70Ue5DX1csebWZwP:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5bacab83a6147fc920a06b7d8a2cebd41eb4c6a0/computeRevoluteJacobianNum.m#L26)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Right- this is what I meant.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianNum.m, line 37 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTc4OKP-ayYT1hdGVmt:-LTc7BC59895D-rzTnsK:b-hztptu) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/8f9c0a8c17f2bf4913d075716a5e531e6c8fcada/computeRevoluteJacobianNum.m#L37)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The partials aren't coming through here. I happen to know that partials show up fine in reviewable. Whether they work in MATLAB is a different story... If you can't use the character, a satisfactory replacement is "d".
</blockquote></details>

partials do show up in MATLAB...  changed with d
Done.


<!-- Sent from Reviewable.io -->

2018-12-13 17:01 UTC, edrumwri approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 1 unresolved discussion (waiting on @rleontie)



<!-- Sent from Reviewable.io -->

2018-12-13 17:53 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[computeRevoluteJacobianNum.m, line 9 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTc3OKy1XP8ixk8brn-:-LTcgN1K9bEH8Z-3zxeb:b-896fjx) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/8f9c0a8c17f2bf4913d075716a5e531e6c8fcada/computeRevoluteJacobianNum.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

nit "in the body" -> "expressed in the body"
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-12-13 21:46 UTC, rleontie commented
Evan, please let me do another revision to update some things before I have you review 





<!-- Sent from Reviewable.io -->

2018-12-13 22:28 UTC, edrumwri requested changes
checkpoint

> Reviewed 3 of 5 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-:-LTdfma32niDzOEU06en:b-vv2shf)* status: 8 of 9 files reviewed, 11 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJointConstraints.m, line 6 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdd2rrABn3xSrfGE55:-LTdd2rrABn3xSrfGE56:b-m1119u) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6cf70eaf4c0643ce3d420c391145bd80cad0c6fa/computeRevoluteJointConstraints.m#L6)):*
> ```objc
> %       two additional constraints. The two additional constraints are for 
> %       vector vi and vj to be parallel. 
> %   fDotRevolute as the first derivative of the f using the analytical derivation.
> ```

Nit "the f" -> "f"
___
*[computeRevoluteJointConstraints.m, line 20 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTddF9E7ugVMK7uxf-1:-LTddF9E7ugVMK7uxf-2:b-31lq6b) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6cf70eaf4c0643ce3d420c391145bd80cad0c6fa/computeRevoluteJointConstraints.m#L20)):*
> ```objc
> %       velocity: values 1:3 in the format vx vy vz
> %       angular velocity: values 4:6 in the format wx wy wz
> %       If velocity is not passed the fDotRevolute is zeros(5,1);
> ```

Nit "passed" -> "provided", "the fDotRevolute is " -> "then fDotRevolute will be zeros(5,1) on return"
___
*[computeRevoluteJointConstraints.m, line 40 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTddXUE6VR19GAeb9u7:-LTddXUE6VR19GAeb9u8:baksr2o) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6cf70eaf4c0643ce3d420c391145bd80cad0c6fa/computeRevoluteJointConstraints.m#L40)):*
> ```objc
>     
>     if exist('velocity','var') 
>      % the velocity is passed as an argument.
> ```

Nit please indent two spaces to make it clearer what is indented.
___
*[computeRevoluteJointConstraints.m, line 47 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTde6ix8oBNiDdfrOzW:-LTde6ix8oBNiDdfrOzX:b-tz5kso) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6cf70eaf4c0643ce3d420c391145bd80cad0c6fa/computeRevoluteJointConstraints.m#L47)):*
> ```objc
>      revVectorsDot = viw' * angularVelTensor *  vjw;
>      [fSpherical fDotSpherical] = computeSphericalJointConstraints(ui, pose, velocity);
>      fDotRevolute = [fDotSpherical; revVectorsDot; revVectorsDot];
> ```

It's not apparent to me why you repeat revVectorsDot- if that's intended, you need documentation for why that's correct.
___
*[computeRevoluteJointConstraints.m, line 49 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTddhXG5k7gm1HztaGO:-LTddhXG5k7gm1HztaGP:bv4d9bl) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6cf70eaf4c0643ce3d420c391145bd80cad0c6fa/computeRevoluteJointConstraints.m#L49)):*
> ```objc
>      fDotRevolute = [fDotSpherical; revVectorsDot; revVectorsDot];
>     else
>         fDotRevolute = zeros(5,1);
> ```

Nit be consistent with your indentation. 2 or 4 spaces.
___
*[getSkewSymmetricMatrix.m, line 2 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfMFj2JX-dEgqZOsb:-LTdfMFj2JX-dEgqZOsc:b3t2v5i) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/getSkewSymmetricMatrix.m#L2)):*
> ```objc
> function skewR = getSkewSymmetricMatrix(v)
> % getSkewSymmetricMatrix(y) generate a skew 3x3 symmetric  marix out a 
> ```

nit sp marix
___
*[getSkewSymmetricMatrix.m, line 2 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfP9J-fmjlV029HLd:-LTdfP9J-fmjlV029HLe:b3x6uox) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/getSkewSymmetricMatrix.m#L2)):*
> ```objc
> function skewR = getSkewSymmetricMatrix(v)
> % getSkewSymmetricMatrix(y) generate a skew 3x3 symmetric  marix out a 
> ```

nit two many spaces after symmetric
___
*[getSkewSymmetricMatrix.m, line 2 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfXu85CAVI-N25tSC:-LTdfXu85CAVI-N25tSD:bouap95) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/getSkewSymmetricMatrix.m#L2)):*
> ```objc
> function skewR = getSkewSymmetricMatrix(v)
> % getSkewSymmetricMatrix(y) generate a skew 3x3 symmetric  marix out a 
> ```

nit "skew 3x3 symmetric" -> "3x3 skew symmetric"
___
*[getSkewSymmetricMatrix.m, line 2 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdf_p15Ztq116LjZ2a:-LTdf_p15Ztq116LjZ2b:bl7ckcv) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/getSkewSymmetricMatrix.m#L2)):*
> ```objc
> function skewR = getSkewSymmetricMatrix(v)
> % getSkewSymmetricMatrix(y) generate a skew 3x3 symmetric  marix out a 
> ```

nit "out" -> "from"
___
*[getSkewSymmetricMatrix.m, line 3 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfclDDQXJEdQAr0Mv:-LTdfclDDQXJEdQAr0Mw:b2j5x7f) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/getSkewSymmetricMatrix.m#L3)):*
> ```objc
> function skewR = getSkewSymmetricMatrix(v)
> % getSkewSymmetricMatrix(y) generate a skew 3x3 symmetric  marix out a 
> % vector of v.
> ```

nit "of v", "v"
___
*[getSkewSymmetricMatrix.m, line 3 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdffxW-7GDtcDjM4pr:-LTdffxW-7GDtcDjM4ps:b-14of6c) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/getSkewSymmetricMatrix.m#L3)):*
> ```objc
> function skewR = getSkewSymmetricMatrix(v)
> % getSkewSymmetricMatrix(y) generate a skew 3x3 symmetric  marix out a 
> % vector of v.
> ```

nit "vector" -> "3-dimensional vector"


<!-- Sent from Reviewable.io -->

2018-12-13 22:31 UTC, edrumwri requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 15 unresolved discussions (waiting on @rleontie)

___
*[TestcomputeRevoluteJacobianNum.m, line 10 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfv5g9_dqQf3hj8bE:-LTdfv5g9_dqQf3hj8bF:bkeb51i) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L10)):*
> ```objc
>         function testComputationNoVelocity(testCase)
>             % testComputationIdentity tests computation with identity rotation.
>             ui = [-1 0 0]'; 
> ```

I suggest making this a completely nonzero vector (like -1 -1 -1).
___
*[TestcomputeRevoluteJacobianNum.m, line 11 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfy_82fU_Wbck6lp1:-LTdfy_82fU_Wbck6lp2:b4fbc70) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L11)):*
> ```objc
>             % testComputationIdentity tests computation with identity rotation.
>             ui = [-1 0 0]'; 
>             pose = [1 0 0 1 0 0 0]';
> ```

I suggest making this a non-identity orientation.
___
*[TestcomputeRevoluteJacobianNum.m, line 14 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdgBMr3hCm0N9_jaJ1:-LTdgBMr3hCm0N9_jaJ2:b-nv9cuf) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L14)):*
> ```objc
>             vi = [0 1 0]'; 
>             vj = [0 1 0]';  
>             velocity = zeros(6,1);
> ```

You definitely don't want to use a zero velocity here.
___
*[TestcomputeRevoluteJacobianNum.m, line 15 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdgIm740rzcNipCino:-LTdgIm740rzcNipCinp:b-hxk4dp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L15)):*
> ```objc
>             vj = [0 1 0]';  
>             velocity = zeros(6,1);
>             actSol = computeRevoluteJacobianNum(ui, vi, vj, pose, deg2rad(1/32)) * velocity;
> ```

Rather than using deg2rad(1/32), I'd just go with the "h" I suggested before: 1e-6. That's about the best that one can do.


<!-- Sent from Reviewable.io -->

2018-12-13 23:36 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 47 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTde6ix8oBNiDdfrOzW:-LTduLS97O_x5i-Uxinc:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6cf70eaf4c0643ce3d420c391145bd80cad0c6fa/computeRevoluteJointConstraints.m#L47)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It's not apparent to me why you repeat revVectorsDot- if that's intended, you need documentation for why that's correct.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 10 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfv5g9_dqQf3hj8bE:-LTdv0kUBUmivx5bSOmC:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I suggest making this a completely nonzero vector (like -1 -1 -1).
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 11 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdfy_82fU_Wbck6lp1:-LTdv1d21uj-zQHBUeWK:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L11)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I suggest making this a non-identity orientation.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 14 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdgBMr3hCm0N9_jaJ1:-LTdv2sx89co6yv0Xg9z:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You definitely don't want to use a zero velocity here.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 15 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdgIm740rzcNipCino:-LTdv6Mf-WLuKGWgyat6:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L15)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Rather than using deg2rad(1/32), I'd just go with the "h" I suggested before: 1e-6. That's about the best that one can do.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 6 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdvLWpCvQd0X302Vsv:-LTdvLWq812cdiVtAcF2:b-eslzre) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/TestcomputeRevoluteJacobianNum.m#L6)):*
> ```objc
>     properties
>     end
>     
> ```

Definitely, broke my test tolerance


<!-- Sent from Reviewable.io -->

2018-12-13 23:51 UTC, edrumwri requested changes
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 3 unresolved discussions (waiting on @rleontie)

___
*[computeSphericalJointConstraints.m, line 14 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdyh0O8dojF2atBDxl:-LTdyh0O8dojF2atBDxm:b-45ghp2) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/computeSphericalJointConstraints.m#L14)):*
> ```objc
> %       angular velocity: values 4:6 in the format wx wy wz
> %       If velocity is not provided then fDotSpherical will be zeros(5,1) on
> %       return.
> ```

I think you have to test this case (that it returns zero).
___
*[TestcomputeRevoluteJacobianNum.m, line 14 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdgBMr3hCm0N9_jaJ1:-LTdy1lk047Zxm2JQW_e:bcjos2e) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L14)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Zeros can hide things. I'd suggest [1 2 3 4 5 6]';


<!-- Sent from Reviewable.io -->

2018-12-14 00:31 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 47 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTe6SBo8g-Ocl7THZXA:-LTe6SBo8g-Ocl7THZXB:b3qhe0x) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/computeRevoluteJointConstraints.m#L47)):*
> ```objc
>         % constraints for vi and vj vectors are in the form: f = v1iw' * vjw , then 
>         % df/dt =  v1iw' * angularVelTensor * vjw, 
>         fDotRevolute = [fDotSpherical; v1iw' * angularVelTensor *  vjw; v2iw' * angularVelTensor *  vjw];
> ```

I have an error in my derivation, right? I see there is an error in the sign but I can't seem to find the error in my parallel vectors derivation
___
*[computeSphericalJointConstraints.m, line 14 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdyh0O8dojF2atBDxl:-LTdzn11COcryG03HZDV:bs7wumb) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/computeSphericalJointConstraints.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I think you have to test this case (that it returns zero).
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 14 at r5](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTdgBMr3hCm0N9_jaJ1:-LTe1deA6ELCnkSpFJbw:bmtpakp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/2fb8b6570e36af29d9248bfde205d5d1c89acfe2/TestcomputeRevoluteJacobianNum.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Zeros can hide things. I'd suggest [1 2 3 4 5 6]';
</blockquote></details>

i see ....


<!-- Sent from Reviewable.io -->

2018-12-14 15:23 UTC, edrumwri requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 3 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJacobianNum.m, line 5 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThHueX37tMYOfedVhJ:-LThHueX37tMYOfedVhK:b-5ajlws) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/computeRevoluteJacobianNum.m#L5)):*
> ```objc
> %   JRevNum a 5x6 matrix that estimates numerically the jacobian for the 
> %        revolute joint.
> %   JDotRevNum a 5x6 matrix that estimates numerically the derived jacobian
> ```

Why are you computing and returning this?
___
*[computeRevoluteJointConstraints.m, line 47 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTe6SBo8g-Ocl7THZXA:-LThI4PdEUaLEFMUkc0_:b-2w6f7c) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/computeRevoluteJointConstraints.m#L47)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I have an error in my derivation, right? I see there is an error in the sign but I can't seem to find the error in my parallel vectors derivation
</blockquote></details>

I'd put the math in the comments. v1iw' * vjw is really v1i' * wRi' * wRj * vj. So, compute the time derivative of that, and put the derivation in the comments. I'll check it then.
___
*[TestcomputeSphericalJointConstraints.m, line 27 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThIuCi4Hm4G6GkviUU:-LThIuCi4Hm4G6GkviUV:b-5gwq01) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/TestcomputeSphericalJointConstraints.m#L27)):*
> ```objc
>         end
>         
>         function testNoVelocityInputFDot(testCase)
> ```

Why didn't you introduce the same test for revolute joints?


<!-- Sent from Reviewable.io -->

2018-12-14 15:27 UTC, rleontie commented
___
*[TestcomputeSphericalJointConstraints.m, line 27 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThIuCi4Hm4G6GkviUU:-LThJsOwD0d0ZgZI_r--:b-ytzxd) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/TestcomputeSphericalJointConstraints.m#L27)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why didn't you introduce the same test for revolute joints?
</blockquote></details>

I don't have a unit testing for that function... I will make one in my next commit


<!-- Sent from Reviewable.io -->

2018-12-14 16:48 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJacobianNum.m, line 5 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThHueX37tMYOfedVhJ:-LThO5cN0reOguhXxPJZ:b-miahq4) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/computeRevoluteJacobianNum.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why are you computing and returning this?
</blockquote></details>

I thought you wanted me to calculate the derived Jacobian \dot{JacRevolute}
___
*[computeRevoluteJointConstraints.m, line 47 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTe6SBo8g-Ocl7THZXA:-LThYh7HCdRP50FjJsMg:b-hi7m31) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/computeRevoluteJointConstraints.m#L47)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'd put the math in the comments. v1iw' * vjw is really v1i' * wRi' * wRj * vj. So, compute the time derivative of that, and put the derivation in the comments. I'll check it then.
</blockquote></details>

found my error on my own. Thank you.. I was to tired yesterday :). I think I wrote it like 50 times and made the same mistake.  \dot{wRi'} = wRi' * w_tensor' , the tensor is transposed too. :),  and \transpose{w_tensor} = - w_tensor, so that is why I saw the sign error. 
___
*[TestcomputeSphericalJointConstraints.m, line 27 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThIuCi4Hm4G6GkviUU:-LThbT4O09MYieEzPUfP:b-aodcl1) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/TestcomputeSphericalJointConstraints.m#L27)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I don't have a unit testing for that function... I will make one in my next commit
</blockquote></details>

Done. Added a separate unit test for the revolute joint constraints.


<!-- Sent from Reviewable.io -->

2018-12-14 16:59 UTC, edrumwri requested changes
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 4 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJacobianNum.m, line 5 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThHueX37tMYOfedVhJ:-LThd3GQ56gwNxhnQuro:b-esnfb1) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/computeRevoluteJacobianNum.m#L5)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I thought you wanted me to calculate the derived Jacobian \dot{JacRevolute}
</blockquote></details>

The derived Jacobian is the not the time derivative of the Jacobian. It's the Jacobian computed through calculus derivations, rather than numerically.
___
*[computeRevoluteJointConstraints.m, line 47 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LTe6SBo8g-Ocl7THZXA:-LThdGIKEAogJn1sOqn9:b7l9zqr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/b269d4dd9b694242ed6f9e8e4515ee5ec502ec87/computeRevoluteJointConstraints.m#L47)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

found my error on my own. Thank you.. I was to tired yesterday :). I think I wrote it like 50 times and made the same mistake.  \dot{wRi'} = wRi' * w_tensor' , the tensor is transposed too. :),  and \transpose{w_tensor} = - w_tensor, so that is why I saw the sign error. 
</blockquote></details>

That would explain it. You're cranking out code pretty fast. The good news is that you're finding bugs at this level, rather than encountering them once all of the code is written (there might be some of that too, but the quality of this code should make it much easier to find them!).
___
*[TestcomputeRevoluteJacobianNum.m, line 30 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThdrOh1H8PwPhoEsQ3:-LThdrOh1H8PwPhoEsQ4:b-tgs8yp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/4f838245ed012de802495335b0180ddeb87cfaf2/TestcomputeRevoluteJacobianNum.m#L30)):*
> ```objc
>             actSol = computeRevoluteJacobianNum(ui, vi, vj, pose, 1e-6) * velocity;
>             [fRevolute, expSol] = computeRevoluteJointConstraints(ui, vi, vj, pose, velocity);
>             testCase.verifyEqual(actSol, expSol, 'AbsTol', 400*sqrt(eps));
> ```

Realistically, this is too tight a tolerance here, because your h is 1e-6. You shouldn't expect to get better accuracy than that.
___
*[TestcomputeRevoluteJointConstraints.m, line 33 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThddGUBTRz59B8wC2F:-LThddGUBTRz59B8wC2G:b1ysxof) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/4f838245ed012de802495335b0180ddeb87cfaf2/TestcomputeRevoluteJointConstraints.m#L33)):*
> ```objc
>         function testNoVelocityInputFDot(testCase)
>            % testNoVelocityInputFDot tests if the function returns zeros 
>             %if no velocity for fDot.
> ```

nit: space between % and comment.


<!-- Sent from Reviewable.io -->

2018-12-14 17:22 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJacobianNum.m, line 5 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThHueX37tMYOfedVhJ:-LThhl5q0TeLAwXQ-aed:b6x8cup) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/43c4ac71d49de4bfe7b346e468d26cd6fb9460cd/computeRevoluteJacobianNum.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The derived Jacobian is the not the time derivative of the Jacobian. It's the Jacobian computed through calculus derivations, rather than numerically.
</blockquote></details>

reverted my changes 
___
*[TestcomputeRevoluteJacobianNum.m, line 30 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThdrOh1H8PwPhoEsQ3:-LThfbY4971YMUv76mm1:b-4o3plx) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/4f838245ed012de802495335b0180ddeb87cfaf2/TestcomputeRevoluteJacobianNum.m#L30)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Realistically, this is too tight a tolerance here, because your h is 1e-6. You shouldn't expect to get better accuracy than that.
</blockquote></details>

Done, realistically I was not getting better than that: I was getting 5e-6 to 7e-6
___
*[TestcomputeRevoluteJointConstraints.m, line 33 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThddGUBTRz59B8wC2F:-LThgXhU32hOQrBppBt3:bb6un1j) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/4f838245ed012de802495335b0180ddeb87cfaf2/TestcomputeRevoluteJointConstraints.m#L33)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

nit: space between % and comment.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-12-14 17:50 UTC, edrumwri approved these changes
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: all files reviewed, 2 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJacobianNum.m, line 3 at r10](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4#-LThpgBc84tKiBj-PQxz:-LThpgBc84tKiBj-PQy-:befzk6e) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/8b597655b71c2fb6db9370ccc645ebf84892a34e/computeRevoluteJacobianNum.m#L3)):*
> ```objc
> function JRevNum = computeRevoluteJacobianNum(ui, vi, vj, pose, eps)
> % computeRevoluteJacobianNum(ui, vi, vj, pose, eps) returns a 5x6 matrix that estimates 
> % numerically the jacobian for the spherical joint.
> ```

Nit spherical -> revolute


<!-- Sent from Reviewable.io -->

2018-12-14 18:01 UTC, edrumwri approved these changes
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-14 18:05 UTC, merged