JacobianDot files for revolute and spherical
edrumwri/revolute-joint-parameter-estimation pull request #5
Opened 2018-12-14 21:05 UTC by rleontie

2018-12-14 22:48 UTC, edrumwri reviewed
Why are you calculating the time derivative of the Jacobian? We shouldn't actually need to do that.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LTiturd9O0tDV191B9o:b-bb4p0k)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-14 22:50 UTC, rleontie commented
OK... what should I do?





<!-- Sent from Reviewable.io -->

2018-12-14 22:52 UTC, edrumwri reviewed
The Jacobian matrix itself using the derivation that I gave you, perhaps? 

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LTiunVABN8kujAqjFoz:b-cwktoz)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-14 22:58 UTC, rleontie commented
OK, so we did the numerical Jacobian and now we want the analytical right? that is easy... But I thought you wanted the \dot{RevoluteJac}, which is the derivative of that. Can I keep these files? I think we are going to need them anyway. 





<!-- Sent from Reviewable.io -->

2018-12-14 23:37 UTC, edrumwri reviewed
Ok. Remember how we're using the relationship:

\dot{f} = J*v

for testing?

That gives us the relationship:

\ddot{f} = J*\dot{v} + \dot{J}*v

which means that, assuming \dot{v} is zero, \ddot{f} will give you \dot{J}*v. That seems much easier than having to compute the time derivatives of the Jacobians. But you can use the time derivatives of the Jacobians to test your result.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LTj3Fci672ePA3ONdDP:byt8lem)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-15 01:23 UTC, edrumwri reviewed
Roxana, these need unit tests, especially as hairy as this code is.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LTjSTvFDDLLlL2uS62Q:b-tcgcfj)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @rleontie)

___
*[computeRevoluteJacobianAnalytical.m, line 2 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LTjSML95Z274HcV7U4i:-LTjSML95Z274HcV7U4j:bvqhllw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/94fb11eb7d6a36718d4fcfeeb90bb0b02c7525c7/computeRevoluteJacobianAnalytical.m#L2)):*
> ```objc
> function JRev = computeRevoluteJacobianAnalytical(ui, vi, vj, quat)
> % computeRevoluteJacobianAnalytica analytical computation of the jacobian
> ```

Nit "Analytica"


<!-- Sent from Reviewable.io -->

2018-12-17 16:21 UTC, rleontie commented
To apply the method you describe in your earlier comment I need to calculate \ddot{f}? I am working on some unit tests...





<!-- Sent from Reviewable.io -->

2018-12-17 17:46 UTC, edrumwri reviewed
Right.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LTxGeKQ9IBtl28h0Xk7:byr4flj)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @rleontie)



<!-- Sent from Reviewable.io -->

2018-12-17 17:50 UTC, rleontie commented
how do I calculate \ddot{f}? I tried estimating that numerically and told me that is not the way.  I also looked at doing the analytical calculation by deriving the analytical version of \dot{f} but I am getting in a weird relationship that I can not simplify. Should I send you my calculations?  Can we assume that w is 0 too?





<!-- Sent from Reviewable.io -->

2018-12-17 17:57 UTC, edrumwri reviewed
Yes, analytical derivation is the way. Do not assume that w is zero. Send me your calculations if you need to simplify it (I don't understand why you need to simplify it) and can't do so.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LTxJ2mn8QQN0ROXKxLx:b-jqhsdy)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @rleontie)



<!-- Sent from Reviewable.io -->

2018-12-18 21:21 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 0 of 11 files reviewed, 4 unresolved discussions

___
*[computeRevoluteJacobianDot.m, line 13 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2A57g-2O57KNQwNsh:-LU2A57g-2O57KNQwNsi:bksryw4) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDot.m#L13)):*
> ```objc
>   JSphericalDot = computeSphericalJacobianDot(ui, quat, quatDot);
>   
>   [v1i, v2i] = computeBasisFromAxis(vi);   
> ```

here the basis vectors are computed in the local i frame. 
___
*[computeRevoluteJointConstraints.m, line 38 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU28YDp4KI3zz3wSZ07:-LU28YDp4KI3zz3wSZ08:bm7z43f) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L38)):*
> ```objc
>     vjw = wRj * vj; 
> 
>     [v1iw, v2iw] = computeBasisFromAxis(viw);
> ```

is it a problem I am getting the basis vectors in the global frame?
___
*[computeRevoluteJointConstraints.m, line 66 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU27PUB9rMLBAi-Va9i:-LU27PUB9rMLBAi-Va9j:bapnh8o) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L66)):*
> ```objc
>             %           + (wRi * vxi)' * skew(vjw) * \dot{angulatVel}
>             fDDotRevolute = [fDDotSpherical; ... 
>                 v1iw' *  angularVelTensor * skewvjw * angularVel + v1iw' * skewvjw * angularVelDot;...
> ```

there is a problem here I think, and I don't seem to figure it out. The two revolute constraint values are switched between this numerical and analytical solution, and one has a minus sign the other doesn't.  So I posted a few comments for us to look at together if you can. 
___
*[TestcomputeRevoluteJacobianDotNum.m, line 21 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2BOur7NMqkIzthA9r:-LU2BOur7NMqkIzthA9s:b67nxob) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeRevoluteJacobianDotNum.m#L21)):*
> ```objc
>             actSol = computeRevoluteJacobianDotNum(ui, vi, vj, pose, velocity, acceleration, 1e-6);
>             expSol = computeRevoluteJacobianDot(ui, vi, vj, pose(4:7), quatDot) * velocity;
>             testCase.verifyEqual(actSol, expSol, 'AbsTol', 5e-6);
> ```

this test fails... here is the output: 

 Actual Value:
      64.999998760034970
      62.000003299120870
     -95.000001450862143
      10.000001702799368
      50.000010536071628
    Expected Value:
      65.000003458811207
      62.000003299173763
     -95.000005055185611
      50.000002660624006
     -10.000000532124801


<!-- Sent from Reviewable.io -->

2018-12-18 21:42 UTC, edrumwri requested changes
Checkpoint.

> Reviewed 1 of 3 files at r2, 3 of 9 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU2GI1f2JQqa4HmZW2I:by96gdd)* status: 5 of 11 files reviewed, 11 unresolved discussions (waiting on @rleontie)

___
*[computeQuatDot.m, line 3 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2CxGe5xhKlafvAwaT:-LU2CxGf9_7fWfMHol7Q:b-z9g7g8) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeQuatDot.m#L3)):*
> ```objc
> function eDot = computeQuatDot(quat, angularVelocity)
> % computeQuatDot Calculates the derivative of the quaternion
> %   Based of Nikravesh formula 6.104 \dot{quat} = 1/2 * G' * w
> ```

Nit "Based on" or "Based off of"
___
*[computeRevoluteJacobianAnalytical.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FvfECXOvw1W0YixE:-LU2FvfECXOvw1W0YixF:bdjwswp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianAnalytical.m#L4)):*
> ```objc
> % computeRevoluteJacobianAnalytical analytical computation of the jacobian
> % for the revolute joint.
> %   JRev = [eye(3)      -skew(wRi * ui); % Spherical Jacobian
> ```

I'm having to trust that you've done the math right, but why make me trust it? Why not put your derivations right here in the documentation? You can use unicodeit to help format them as well.
___
*[computeRevoluteJacobianDotNum.m, line 1 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2EPjT90IJLE-_BVQu:-LU2EPjU45CK6NsvnO13:bou5vbp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDotNum.m#L1)):*
> ```objc
> function JacDotTimesVel = computeRevoluteJacobianDotNum(ui, vi, vj, pose, velocity, acceleration, eps)
> ```

The function name is no longer representative. Perhaps `computeRevoluteJacobianDotV`? (I don't think you want to use the numerical Jacobian, see next comment).
___
*[computeRevoluteJacobianDotNum.m, line 7 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2ElUZBi27HMzMqFoh:-LU2ElUZBi27HMzMqFoi:b-553csk) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDotNum.m#L7)):*
> ```objc
> 
>     [fRevolute, fDRevolute, fDDRevolute] = computeRevoluteJointConstraints(ui, vi, vj, pose, velocity, acceleration);
>     revJac = computeRevoluteJacobianNum(ui, vi, vj, pose, eps);
> ```

I think you want the derived Jacobian here, since it's more accurate.
___
*[computeRevoluteJointConstraints.m, line 38 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU28YDp4KI3zz3wSZ07:-LU2F26Q9_OOCS7TsJ1r:b-7ds8yb) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L38)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

is it a problem I am getting the basis vectors in the global frame?
</blockquote></details>

No, that's no worse than computing the basis vectors in the local frame and then transforming them to the global frame. Both should be fine.
___
*[computeRevoluteJointConstraints.m, line 56 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FByWBhKVGWp4YiXW:-LU2FByWBhKVGWp4YiXX:bkrdxd7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L56)):*
> ```objc
>         fDotRevolute = [fDotSpherical; v1iw' * angularVelTensor' *  vjw; v2iw' * angularVelTensor' *  vjw];
>         
>         if exist('acceleration','var')
> ```

Nit space after comma
___
*[computeRevoluteJointConstraints.m, line 61 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FFNq2If0oTDnKm66:-LU2FFNq2If0oTDnKm67:b-eucgrc) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L61)):*
> ```objc
>             angularVel = velocity(4:6);
>             angularVelDot = acceleration(4:6);
>             % for the revolute constraints derivative we derive 
> ```

Nit constraints' (apostrophe needed)
___
*[computeSphericalJacobianDot.m, line 1 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FUv2AtPOEKq1vllT:-LU2FUv2AtPOEKq1vllU:b-7hd0dj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJacobianDot.m#L1)):*
> ```objc
> function JSphericalDot = computeSphericalJacobianDot(ui, quat, quatDot)
> ```

We really never need \dot{J}, just \dot{J} * v. And, since \dot{J} can be hard to obtain (like for the revolute joint), I suggest just having this method return \dot{J} * v to provide a consistent API.


<!-- Sent from Reviewable.io -->

2018-12-19 00:03 UTC, edrumwri requested changes
> Reviewed 2 of 9 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 8 of 11 files reviewed, 21 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJacobianDot.m, line 1 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2G_tz3R1Wvz36FZD9:-LU2G_tz3R1Wvz36FZDA:bdievu0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDot.m#L1)):*
> ```objc
> function JRevDot = computeRevoluteJacobianDot(ui, vi, vj, quat, quatDot)
> ```

Same comment as I provided in the spherical joint version: just have this return \dot{J} * v.
___
*[computeSphericalJointConstraints.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2GpOJ5kSvTVfHIfdb:-LU2GpOJ5kSvTVfHIfdc:b-tmv1im) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJointConstraints.m#L4)):*
> ```objc
> % computeSphericalJointConstraints(ui, pose, velocity) computes:
> %   fSpherical: the spherical joint constraints defined as x + R * u = 0.
> %   fDotSpherical: as the first derivative of fSpherical using the analytical derivation.
> ```

Nit you now need to document the third output.
___
*[computeSphericalJointConstraints.m, line 38 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2Gv28D2D9q__Why76:-LU2Gv28D2D9q__Why77:br624l8) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJointConstraints.m#L38)):*
> ```objc
>         fDotSpherical = vel + angularVelTensor * wRi * ui;    
>         
>         if exist('acceleration','var')
> ```

Nit space after the comma
___
*[computeSphericalJointConstraints.m, line 39 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2GzQJ59J9fs-KMT7e:-LU2GzQJ59J9fs-KMT7f:bxg4tsv) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJointConstraints.m#L39)):*
> ```objc
>         
>         if exist('acceleration','var')
>             % for the revolute constraints derivative we derive 
> ```

Nit missing apostrophe after "constraints"
___
*[computeSphericalJointConstraints.m, line 42 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2H2OU-R1dSyu6geie:-LU2H2OU-R1dSyu6geif:bzh5i3c) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJointConstraints.m#L42)):*
> ```objc
>             % \dot{f} = vel + w x (wRi * ui) , which is 
>             % \ddot{f} = \dot{vel} + \dot{w} x (wRi * ui)  
>             %           + w x (w x(wRi * ui)).
> ```

Nit missing space after the second cross product.
___
*[computeSphericalJointConstraints.m, line 43 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2Pm0v6m-9IzMPpz5A:-LU2Pm0w3WfhQQ1pVIOC:bh6lzr3) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJointConstraints.m#L43)):*
> ```objc
>             % \ddot{f} = \dot{vel} + \dot{w} x (wRi * ui)  
>             %           + w x (w x(wRi * ui)).
>             uiw = wRi * ui;
> ```

I should have caught this before, and I'm afraid you have it all over the place. `ui` is the "u" vector defined in the body "i" frame. When it's transformed to the global frame, it should become `uw`, not `uiw`.
___
*[TestcomputeRevoluteJointConstraints.m, line 43 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2QU1C9kABYYEyeM2X:-LU2QU1C9kABYYEyeM2Y:bc80m2e) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeRevoluteJointConstraints.m#L43)):*
> ```objc
>         end
>         
>         function testNoVelocityNoAccelerationInputFDDot(testCase)
> ```

This test is mislabelled- it isn't "no velocity and no acceleration". It's only no acceleration.
___
*[TestcomputeRevoluteJointConstraints.m, line 50 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2QSGG3fm_4SCVR088:-LU2QSGG3fm_4SCVR089:b4az8mb) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeRevoluteJointConstraints.m#L50)):*
> ```objc
>             vj = [0 1 0]'; 
>             pose = [1 0 0 0.7071068 0 0.7071068 0]';
>             [fRev,fDRev, actSol] = computeRevoluteJointConstraints(ui, vi, vj, pose);
> ```

Nit space after comma.
___
*[TestcomputeSphericalJointConstraints.m, line 37 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2lQhW3xOmCAi4nlJA:-LU2lQhX3-tYLApZ1CUG:b-680mum) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeSphericalJointConstraints.m#L37)):*
> ```objc
>         end
>         
>         function testNoVelocityNoAccelerationInputFDDot(testCase)
> ```

Same comment here about "NoVelocity" name.
___
*[TestcomputeSphericalJointConstraints.m, line 42 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2lUFj5WXwGPEQd8oS:-LU2lUFj5WXwGPEQd8oT:b4az8mb) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeSphericalJointConstraints.m#L42)):*
> ```objc
>             ui = [-1 0 0]';
>             pose = [1 0 0 0.7071068 0 0.7071068 0]';
>             [fSpherical,fDSpherical, actSol] = computeSphericalJointConstraints(ui, pose);
> ```

Nit space after comma.


<!-- Sent from Reviewable.io -->

2018-12-19 00:11 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 8 of 11 files reviewed, 22 unresolved discussions (waiting on @rleontie)

___
*[computeRevoluteJointConstraints.m, line 62 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2n4PN4tm0OfiLxxBX:-LU2n4PN4tm0OfiLxxBY:b4fyzk0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L62)):*
> ```objc
>             angularVelDot = acceleration(4:6);
>             % for the revolute constraints derivative we derive 
>             % \dot{f} = (wRi * vxi)' * skew(vjw) * angularVel, which is 
> ```

Are you assuming that vjw is not a function of time? I'm confused b/c if it is, then I don't know why you'd have the skew(.) operator here. If not assuming that, this term should be much more complicated.


<!-- Sent from Reviewable.io -->

2018-12-19 00:29 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 1 of 12 files reviewed, 12 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeSphericalJointConstraints.m, line 43 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2Pm0v6m-9IzMPpz5A:-LU2oJ2l4ffM32aRX0xF:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJointConstraints.m#L43)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I should have caught this before, and I'm afraid you have it all over the place. `ui` is the "u" vector defined in the body "i" frame. When it's transformed to the global frame, it should become `uw`, not `uiw`.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJointConstraints.m, line 43 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2QU1C9kABYYEyeM2X:-LU2p5sU2N7DeC-1rnrT:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeRevoluteJointConstraints.m#L43)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This test is mislabelled- it isn't "no velocity and no acceleration". It's only no acceleration.
</blockquote></details>

Done.
___
*[TestcomputeSphericalJointConstraints.m, line 37 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2lQhW3xOmCAi4nlJA:-LU2p6x99QUStjiBaTPD:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeSphericalJointConstraints.m#L37)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Same comment here about "NoVelocity" name.
</blockquote></details>

Done.
___
*[computeSphericalJacobianDot.m, line 1 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FUv2AtPOEKq1vllT:-LU2q2sl6A4PrMocP1Xb:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeSphericalJacobianDot.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

We really never need \dot{J}, just \dot{J} * v. And, since \dot{J} can be hard to obtain (like for the revolute joint), I suggest just having this method return \dot{J} * v to provide a consistent API.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-19 01:02 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 0 of 12 files reviewed, 10 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 62 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2n4PN4tm0OfiLxxBX:-LU2xuxy1_eta-qUWjNi:b683tst) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L62)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Are you assuming that vjw is not a function of time? I'm confused b/c if it is, then I don't know why you'd have the skew(.) operator here. If not assuming that, this term should be much more complicated.
</blockquote></details>

I am assuming that vjw is not a function of time. The reason I have that is because I wanted to separate angular velocity to the right.
___
*[TestcomputeRevoluteJacobianDotNum.m, line 21 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2BOur7NMqkIzthA9r:-LU2yo3-4IscOE4C8cJc:bvspnda) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeRevoluteJacobianDotNum.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

this test fails... here is the output: 

 Actual Value:
      64.999998760034970
      62.000003299120870
     -95.000001450862143
      10.000001702799368
      50.000010536071628
    Expected Value:
      65.000003458811207
      62.000003299173763
     -95.000005055185611
      50.000002660624006
     -10.000000532124801
</blockquote></details>

test still fails. 

Actual Value:
      65.000004469848335
      62.000003192748807
     -95.000005640522900
      24.000003086323854
      60.000010748921540
    Expected Value:
      65.000003458811207
      62.000003299173763
     -95.000005055185611
      50.000002660624006
     -10.000000532124801
___
*[computeRevoluteJacobianAnalytical.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FvfECXOvw1W0YixE:-LU2st0lASUkSIQv0Mrp:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianAnalytical.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'm having to trust that you've done the math right, but why make me trust it? Why not put your derivations right here in the documentation? You can use unicodeit to help format them as well.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianDot.m, line 1 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2G_tz3R1Wvz36FZD9:-LU2ycOmAtMrBkUpS-eC:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDot.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Same comment as I provided in the spherical joint version: just have this return \dot{J} * v.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianDotNum.m, line 1 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2EPjT90IJLE-_BVQu:-LU2rtII6qydfPHZPAHP:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDotNum.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The function name is no longer representative. Perhaps `computeRevoluteJacobianDotV`? (I don't think you want to use the numerical Jacobian, see next comment).
</blockquote></details>

Done.
___
*[computeRevoluteJacobianDotNum.m, line 7 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2ElUZBi27HMzMqFoh:-LU2s_tj9Ep2xcURawHp:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianDotNum.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I think you want the derived Jacobian here, since it's more accurate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-19 14:28 UTC, rleontie commented
Checkpoint?





<!-- Sent from Reviewable.io -->

2018-12-19 15:37 UTC, edrumwri requested changes
I'm not seeing a test for comparing the numerical Jacobians against the analytical versions (*not* the \dot{J}v tests). Am I missing them?

> Reviewed 8 of 12 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU6-5spC1gABCUXu0Ml:b-12hqxj)* status: all files reviewed, 13 unresolved discussions (waiting on @rleontie and @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 62 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2n4PN4tm0OfiLxxBX:-LU63DTk1VZ1JhNI4UT_:b309aeu) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L62)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

I am assuming that vjw is not a function of time. The reason I have that is because I wanted to separate angular velocity to the right.
</blockquote></details>

This is my derivation, which I did from vjw' * wRi * vxi. I plugged this into Matlab and the numbers don't seem to match yours. Please check this more thoroughly. I suspect this is where your bug is.

d/dt vjw' * wRi * vxi = vjw' * \omega x (wRi * vxi)
d^2/dt^2 vjw' * wRi * vxi = vjw' * \alpha x (wRi * vxi) + vjw' * \omega x \omega x (wRi * vxi)
___
*[computeSphericalJointConstraints.m, line 4 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU628Bg4Gjk1FuOWJ9c:-LU628Bg4Gjk1FuOWJ9d:b2gp4mr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeSphericalJointConstraints.m#L4)):*
> ```objc
> % computeSphericalJointConstraints(ui, pose, velocity) computes:
> %   fSpherical: the spherical joint constraints defined as x + R * u = 0.
> %   fDotSpherical: as the first derivative of fSpherical using the analytical derivation.
> ```

Nit I'd recommend dropping "using the analytical derivation" from both comments- it doesn't add any information.
___
*[TestcomputeRevoluteJacobianDotV.m, line 21 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62u12C8mduu4X4inP:-LU62u12C8mduu4X4inQ:b-58vglr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianDotV.m#L21)):*
> ```objc
>             actSol = computeRevoluteJacobianDotV(ui, vi, vj, pose, velocity, acceleration);
>             expSol = computeRevoluteJacobianDotVAnalytical(ui, vi, vj, pose(4:7), quatDot, velocity);
>             testCase.verifyEqual(actSol, expSol, 'AbsTol', 5e-6);
> ```

Since these tests are all using derived quantities, you should be able to use a much tighter tolerance here and below.
___
*[TestcomputeRevoluteJacobianNum.m, line 17 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62RvEEdBi62LCGkEk:-LU62RvEEdBi62LCGkEl:b-aafyx3) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianNum.m#L17)):*
> ```objc
>             actSol = computeRevoluteJacobianDotV(ui, vi, vj, pose, 1e-6) * velocity;
>             [fRevolute, expSol] = computeRevoluteJointConstraints(ui, vi, vj, pose, velocity);
>             testCase.verifyEqual(actSol, expSol, 'AbsTol',6.5e-6);
> ```

Since these tests are all using derived quantities, you should be able to use a much tighter tolerance here.
___
*[TestcomputeRevoluteJacobianDotNum.m, line 21 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2BOur7NMqkIzthA9r:-LU2Q7TVA7-q8AsIpk5E:b-es5mfb) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/TestcomputeRevoluteJacobianDotNum.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

test still fails. 

Actual Value:
      65.000004469848335
      62.000003192748807
     -95.000005640522900
      24.000003086323854
      60.000010748921540
    Expected Value:
      65.000003458811207
      62.000003299173763
     -95.000005055185611
      50.000002660624006
     -10.000000532124801
</blockquote></details>

I'm not ignoring the failing test. My rule is to address all of the obvious stuff first, and then work on sussing out the bug.
___
*[computeRevoluteJacobian.m, line 11 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU5z1_Z62WppckjyVJy:-LU5yYXxB1hMYGIhS2in:b-bcyzep) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobian.m#L11)):*
> ```objc
> %   triad vi, v1i and v2i
> %
> %   The revolute constraint is f = (wRi * vxi)' * vjw , 
> ```

What is vxi? Are you saying that stands for both v1i and v2i? If so, add a comment to that effect.
___
*[computeRevoluteJacobian.m, line 12 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU5zeYLDRW5t-IyC3-r:-LU5zeYLDRW5t-IyC3-s:b-gjd0bj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobian.m#L12)):*
> ```objc
> %
> %   The revolute constraint is f = (wRi * vxi)' * vjw , 
> %   \dot{f} = vxi' * \dot{wRi'} * vjw 
> ```

You should probably add some comments about how you get from one step to the next. It's taking me a few seconds longer than I would like to follow each step.
___
*[computeRevoluteJacobianDotV.m, line 7 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU60PMi837AE84Sg7we:-LU60PMi837AE84Sg7wf:bpu5hdz) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobianDotV.m#L7)):*
> ```objc
> 
>     [fRevolute, fDRevolute, fDDRevolute] = computeRevoluteJointConstraints(ui, vi, vj, pose, velocity, acceleration);
>     revJac = computeRevoluteJacobian(ui, vi, vj, pose(4:7));
> ```

When you pass in a "view" into a vector, you should name it with a variable.
___
*[computeRevoluteJacobianDotVAnalytical.m, line 15 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU61E1s0_y-IEduv6O-:-LU61E1tD3eNN0Prtyaj:b3lkzho) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobianDotVAnalytical.m#L15)):*
> ```objc
>   [v1i, v2i] = computeBasisFromAxis(vi);   
>   
>   JRevConstDot1 = computeRevConstrDot(v1i, vj, quat, quatDot);
> ```

Something's wrong- this function isn't in this PR or the repo? Am I missing something?
___
*[computeSphericalJacobian.m, line 7 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU61gL16W3gg_Vdeq7a:-LU61gL21_uJYkZn5vhr:b-92nwpa) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeSphericalJacobian.m#L7)):*
> ```objc
> 
>   wRi = qt2rot(quat);
>   JSpherical = [eye(3) -getSkewSymmetricMatrix(wRi * ui)];
> ```

You should add a comment here providing the derivation for this so that I can check it.
___
*[computeSphericalJacobianDotV.m, line 10 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU61ryXDVuJa2w_KPgI:-LU61ryY9zjrx5_2N3au:byw5o90) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeSphericalJacobianDotV.m#L10)):*
> ```objc
>  qwDot = quatDot(1); qxDot = quatDot(2); qyDot = quatDot(3); qzDot = quatDot(4); 
> 
>  JSphericalDot = [0, 0, 0, 0, 2*((-(qwDot*qy) - qw*qyDot + qxDot*qz + qx*qzDot)*ui(1) + (qwDot*qx + qw*qxDot + qyDot*qz + qy*qzDot)*ui(2) + 2*(qw*qwDot + qz*qzDot)*ui(3)), -2*(qxDot*qy + qx*qyDot + qwDot*qz + qw*qzDot)*ui(1) - 4*( [...]

2018-12-19 20:01 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 3 of 12 files reviewed, 12 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 62 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2n4PN4tm0OfiLxxBX:-LU6mI_oDp79xAOdE3wx:bk4o7n) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJointConstraints.m#L62)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This is my derivation, which I did from vjw' * wRi * vxi. I plugged this into Matlab and the numbers don't seem to match yours. Please check this more thoroughly. I suspect this is where your bug is.

d/dt vjw' * wRi * vxi = vjw' * \omega x (wRi * vxi)
d^2/dt^2 vjw' * wRi * vxi = vjw' * \alpha x (wRi * vxi) + vjw' * \omega x \omega x (wRi * vxi)
</blockquote></details>

I can reach to the same derivation, I think the skew matrix messed up my calculations.  
___
*[TestcomputeRevoluteJacobianDotV.m, line 21 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62u12C8mduu4X4inP:-LU72JPO0QAsArIZS6Ga:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianDotV.m#L21)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Since these tests are all using derived quantities, you should be able to use a much tighter tolerance here and below.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianNum.m, line 17 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62RvEEdBi62LCGkEk:-LU6lMED1Wq7WAB_Elvq:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianNum.m#L17)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Since these tests are all using derived quantities, you should be able to use a much tighter tolerance here.
</blockquote></details>

Done.
___
*[computeRevoluteJacobian.m, line 11 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU5z1_Z62WppckjyVJy:-LU6fyaSBYbY6-UJM3-M:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobian.m#L11)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What is vxi? Are you saying that stands for both v1i and v2i? If so, add a comment to that effect.
</blockquote></details>

Done.
___
*[computeRevoluteJacobian.m, line 12 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU5zeYLDRW5t-IyC3-r:-LU6g-YXCcCD1m5_zWrz:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobian.m#L12)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You should probably add some comments about how you get from one step to the next. It's taking me a few seconds longer than I would like to follow each step.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianDotV.m, line 7 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU60PMi837AE84Sg7we:-LU6gJkK1JJXMPjPA8mM:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobianDotV.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

When you pass in a "view" into a vector, you should name it with a variable.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianDotVAnalytical.m, line 15 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU61E1s0_y-IEduv6O-:-LU6gVn33mAeMb9sSZIU:b-fm5eei) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeRevoluteJacobianDotVAnalytical.m#L15)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Something's wrong- this function isn't in this PR or the repo? Am I missing something?
</blockquote></details>

it is in this file line 25.
___
*[computeRevoluteJacobianDotVAnalytical.m, line 25 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU6ga8i6dXNbWZJZh0w:-LU6ga8i6dXNbWZJZh0x:b-2n0n6d) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/39e6af0f9d100000af753d20e6114f38affb0ee8/computeRevoluteJacobianDotVAnalytical.m#L25)):*
> ```objc
> end
> 
> function JRevConstrDot = computeRevConstrDot(vxi, vj, quat, quatDot)
> ```

computeRevConstrDot function definition starts here.
___
*[computeSphericalJacobian.m, line 7 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU61gL16W3gg_Vdeq7a:-LU6v_oa6wsVf2v7p-s_:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeSphericalJacobian.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You should add a comment here providing the derivation for this so that I can check it.
</blockquote></details>

Done.
___
*[computeSphericalJacobianDotV.m, line 10 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU61ryXDVuJa2w_KPgI:-LU6tZ4kDmXtPRIyIDzN:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/computeSphericalJacobianDotV.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

In the past, I've provided the mathematica commands that I used to generate this mass of code in comments, in case I needed to alter them.
</blockquote></details>

Done.
___
*[computeRevoluteJacobianAnalytical.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FvfECXOvw1W0YixE:-LU6flz3AqGymNJ7m_xy:b-83o2bs) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianAnalytical.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It still needs another step to say how you get the Jacobian out of this.
</blockquote></details>

Done. Could this still have a bug in it? This is my guess for the derivation. 


<!-- Sent from Reviewable.io -->

2018-12-19 20:21 UTC, rleontie commented
checkpoint





<!-- Sent from Reviewable.io -->

2018-12-19 21:46 UTC, edrumwri requested changes
> Reviewed 1 of 9 files at r3, 8 of 9 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 13 of 14 files reviewed, 7 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[TestcomputeRevoluteJacobianDotV.m, line 21 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62u12C8mduu4X4inP:-LU7QAMe-qW5oY2PvCA-:b-teah69) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianDotV.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1e-6 isn't much tighter. Is that really all the accuracy you're able to get?
___
*[TestcomputeRevoluteJacobianNum.m, line 17 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62RvEEdBi62LCGkEk:-LU7QIqT-EM5MC8-b0rj:b-s9szk1) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianNum.m#L17)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again, 1e-6 is not a very tight tolerance.
___
*[computeRevoluteJacobian.m, line 6 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7EFLS7iP8LCtpf8wS:-LU7EFLT0bt3ptTdrqm4:b-enal7i) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/918979c0c6e9432085cc2ce1c0700cf8d9dc0e11/computeRevoluteJacobian.m#L6)):*
> ```objc
> %   The revolute constraint is f = vjw' * vxiw, where vxiw = wRi * vxi
> % \dot{f} = vjw' *  (\dot{wRi} * vxi)  
> %         = vjw' * w x (wRi * vxi), using a x b = skew(b)' * a
> ```

Something is wrong here. w x (wRi * vxi) is correct, which should give you -(wRi * vxi) x w, or -skew(wRi * vxi)*w. 
___
*[computeRevoluteJacobian.m, line 17 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7MbMF1sWzsmaROR9Z:-LU7MbMF1sWzsmaROR9_:b-rmt3hj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/918979c0c6e9432085cc2ce1c0700cf8d9dc0e11/computeRevoluteJacobian.m#L17)):*
> ```objc
> %   triad vi, v1i and v2i
> %
> %   Since there are no velocity components in the \dot{f} the first 3 terms are 0
> ```

You want to either call this "translational" or "linear" velocity, rather than just "velocity", to be specific.
___
*[computeRevoluteJacobianDotVAnalytical.m, line 25 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU6ga8i6dXNbWZJZh0w:-LU7P3g12sXUxQgsOyAC:b-4hvi0m) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/39e6af0f9d100000af753d20e6114f38affb0ee8/computeRevoluteJacobianDotVAnalytical.m#L25)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

computeRevConstrDot function definition starts here.
</blockquote></details>

Got it.
___
*[computeSphericalJacobian.m, line 7 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7DS9gCzhQx6HpPBbP:-LU7DS9gCzhQx6HpPBbQ:bwivdlh) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/918979c0c6e9432085cc2ce1c0700cf8d9dc0e11/computeSphericalJacobian.m#L7)):*
> ```objc
> %   \dot{f} = \dot{x} + \dot{wRi} * ui
> %           = \dot{x} + skew(w) * (wRi * ui) , using skew(a) * b = -b * skew(a)
> %           = \dot{x} - (wRi * ui) * skew(w) , using a * skew(b) = skew(a) * b
> ```

This line isn't right, because using the product of (wRi * ui) * skew(w) would be a 3x3 matrix, not a 3x1 matrix.
___
*[computeRevoluteJacobianAnalytical.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU2FvfECXOvw1W0YixE:-LU7EUxCCOfi4xYM1RoH:b-2utk5q) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/92cf0e791b7b90e5c15e93ceecaecb1cb3a91014/computeRevoluteJacobianAnalytical.m#L4)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done. Could this still have a bug in it? This is my guess for the derivation. 
</blockquote></details>

Perhaps- see my comment above.


<!-- Sent from Reviewable.io -->

2018-12-19 22:35 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[TestcomputeRevoluteJacobianDotV.m, line 21 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62u12C8mduu4X4inP:-LU7S4Vs8o7dnD4dsOUU:b-iktjuc) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianDotV.m#L21)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

1e-6 isn't much tighter. Is that really all the accuracy you're able to get?
</blockquote></details>

Not able to determine until we fix the bug. Currently, this test is failing. 
___
*[TestcomputeRevoluteJacobianNum.m, line 17 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62RvEEdBi62LCGkEk:-LU6DOSq2BLmxLYBmZql:b-ggs7m6) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianNum.m#L17)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Again, 1e-6 is not a very tight tolerance.
</blockquote></details>

This test doesn't currently pass. I will adjust once the problem is solved
___
*[computeSphericalJacobian.m, line 7 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7DS9gCzhQx6HpPBbP:-LU7ag7jD6s4cRBtAPAF:bvnrpcm) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/918979c0c6e9432085cc2ce1c0700cf8d9dc0e11/computeSphericalJacobian.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This line isn't right, because using the product of (wRi * ui) * skew(w) would be a 3x3 matrix, not a 3x1 matrix.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2018-12-19 22:50 UTC, edrumwri requested changes
> Reviewed 1 of 4 files at r4, 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[TestcomputeRevoluteJacobianNum.m, line 17 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62RvEEdBi62LCGkEk:-LU7eMq0DqLU21IL2Xhl:b-7s89y1) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianNum.m#L17)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

This test doesn't currently pass. I will adjust once the problem is solved
</blockquote></details>

Sorry, my mistake here. This is a perfectly acceptable tolerance for this test, since it does use numerical differentiation.


<!-- Sent from Reviewable.io -->

2018-12-19 22:54 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri)

___
*[TestcomputeRevoluteJacobianNum.m, line 17 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62RvEEdBi62LCGkEk:-LU7f-WN8sDaeBjE5wnj:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianNum.m#L17)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Sorry, my mistake here. This is a perfectly acceptable tolerance for this test, since it does use numerical differentiation.
</blockquote></details>

Done.
___
*[computeRevoluteJacobian.m, line 6 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7EFLS7iP8LCtpf8wS:-LU7bKJC3HcymP8yBDKq:bu2px7g) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/918979c0c6e9432085cc2ce1c0700cf8d9dc0e11/computeRevoluteJacobian.m#L6)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Something is wrong here. w x (wRi * vxi) is correct, which should give you -(wRi * vxi) x w, or -skew(wRi * vxi)*w. 
</blockquote></details>

This is still not giving me the same result as the numerical estimation.... 
___
*[computeRevoluteJacobian.m, line 17 at r9](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7MbMF1sWzsmaROR9Z:-LU7bIBM--o9Mxrvxb5r:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/918979c0c6e9432085cc2ce1c0700cf8d9dc0e11/computeRevoluteJacobian.m#L17)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You want to either call this "translational" or "linear" velocity, rather than just "velocity", to be specific.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-19 23:36 UTC, edrumwri reviewed
Just to clarify: the primary failing test is the analytical vs. numerical revolute joint Jacobian? (I can't test this out at the moment, since I'm at work and don't have MATLAB installed here).

> Reviewed 1 of 9 files at r8, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU7oneX5qdTWhDZF4GE:b-qnb9it)* status: all files reviewed, 1 unresolved discussion (waiting on @edrumwri)



<!-- Sent from Reviewable.io -->

2018-12-19 23:47 UTC, rleontie commented
Yes that is correct

On Wed, Dec 19, 2018, 6:36 PM Evan Drumwright <notifications@github.com
wrote:

> *@edrumwri* commented on this pull request.
>
> Just to clarify: the primary failing test is the analytical vs. numerical
> revolute joint Jacobian? (I can't test this out at the moment, since I'm at
> work and don't have MATLAB installed here).
>
> Reviewed 1 of 9 files at r8, 1 of 3 files at r10.
> *Reviewable
> <https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU7oneX5qdTWhDZF4GE:b-qnb9it>*
> status: all files reviewed, 1 unresolved discussion (waiting on @edrumwri
> <https://github.com/edrumwri>)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edrumwri/revolute-joint-parameter-estimation/pull/5#pullrequestreview-186796572>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZrszPsMqtxFbfLZQtH4tyDN13M4rPnks5u6s1zgaJpZM4ZURCi>
> .
>

2018-12-19 23:58 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: all files reviewed, 2 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJacobian.m, line 12 at r10](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7tgPbBZ69tEdh_DSy:-LU7tgPcC-tTR9QvZgdu:bp70ssy) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/23fd92d599428473894a2c0917d6c10ecaa780c3/computeRevoluteJacobian.m#L12)):*
> ```objc
> 
> %   JRev = [eye(3)     -skew(wRi * ui); ...        % Spherical Jacobian
> %           zeros(1,3) vjw' * -skew(wRi * v1i)'; ...
> ```

You're incorrectly transposing the skew symmetric matrix, here and in the code below.


<!-- Sent from Reviewable.io -->

2018-12-20 00:15 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: all files reviewed, 2 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJacobian.m, line 12 at r10](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU7tgPbBZ69tEdh_DSy:-LU7wCoO1srHe66uYG7n:b-zglfn0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/23fd92d599428473894a2c0917d6c10ecaa780c3/computeRevoluteJacobian.m#L12)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You're incorrectly transposing the skew symmetric matrix, here and in the code below.
</blockquote></details>

OK that was left there from the previous iteration sorry. Numerical and analytical versions still don't match in the revolute constraints, it is a sign error:
Numerical:
  0                   0                   0   1.000000053212480                   0   1.000000053212480
  0                   0                   0   1.000000159637446                   0  -1.00000015963744

Analytical:
 0                   0                   0   1.000000000000000                   0  -1.000000106424960
 0                   0                   0  -1.000000106424960                   0  -1.000000000000000


<!-- Sent from Reviewable.io -->

2018-12-20 02:03 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 13 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 32 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8LNv-9h0Vmugr811X:-LU8LNv-9h0Vmugr811Y:b-kjzr4x) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJointConstraints.m#L32)):*
> ```objc
> 
>     quat = pose(4:7); % quaternion components
>     wRi = quat2R(quat);
> ```

Where is this quat2R function coming from?
___
*[computeRevoluteJacobian.m, line 4 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU87vqHD2sbk-x7GYO8:-LU87vqHD2sbk-x7GYO9:ba0ljg9) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJacobian.m#L4)):*
> ```objc
> % computeRevoluteJacobian analytical computation of the jacobian
> % for the revolute joint.
> %   The revolute constraint is f = vjw' * vxiw, where vxiw = wRi * vxi
> ```

Nit Somehow this vxi has come back, and it's not being explained what it is.
___
*[computeRevoluteJacobian.m, line 4 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU880bP0JqlGuCvXa9G:-LU880bP0JqlGuCvXa9H:b-w3o8r0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJacobian.m#L4)):*
> ```objc
> % computeRevoluteJacobian analytical computation of the jacobian
> % for the revolute joint.
> %   The revolute constraint is f = vjw' * vxiw, where vxiw = wRi * vxi
> ```

vxiw should be vxw.


<!-- Sent from Reviewable.io -->

2018-12-20 02:14 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 32 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8LNv-9h0Vmugr811X:-LU8MEJX2Ega8qCZm396:bapjhaj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJointConstraints.m#L32)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Where is this quat2R function coming from?
</blockquote></details>

waw! It was my previous implementation, good catch! Done. 
___
*[computeRevoluteJacobian.m, line 4 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU880bP0JqlGuCvXa9G:-LU8NMXS-HE2yVoccuk2:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJacobian.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

vxiw should be vxw.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-20 02:20 UTC, edrumwri reviewed
Somehow I let your numerical Jacobian code slip by me. It doesn't run on my system. It says:

Running TestcomputeRevoluteJacobianNum

================================================================================
Error occurred in TestcomputeRevoluteJacobianNum/testNumericalVsAnalyticalJac and it did not run to completion.

    --------------
    Error Details:
    --------------
    Error using  - 
    Matrix dimensions must agree.
    
    Error in computeRevoluteJacobianNum (line 39)
        JRevNum = (fForward - fCurrent) / eps * N;    
    
    Error in TestcomputeRevoluteJacobianNum/testNumericalVsAnalyticalJac (line 19)
                actSol = computeRevoluteJacobianNum(ui, vi, vj, pose,  1e-6); 
    

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU8PRWA53NO5odaLkuJ:b8g5s8d)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @rleontie)



<!-- Sent from Reviewable.io -->

2018-12-20 02:23 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 32 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8LNv-9h0Vmugr811X:-LU8QGaG8NAEsbEjZtOJ:b-1xw5rh) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJointConstraints.m#L32)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

waw! It was my previous implementation, good catch! Done. 
</blockquote></details>

It's in the spherical joint one too.


<!-- Sent from Reviewable.io -->

2018-12-20 02:31 UTC, rleontie commented
I don't get that at all! Are you running the latest version?

>runtests('TestcomputeRevoluteJacobianNum')
Running TestcomputeRevoluteJacobianNum

================================================================================
Verification failed in TestcomputeRevoluteJacobianNum/testNumericalVsAnalyticalJac.

    ---------------------
    Framework Diagnostic:
    ---------------------
    verifyEqual failed.
    --> The values are not equal using "isequaln".
    --> The error was not within absolute tolerance.
    --> Failure table:
            Index    Subscripts         Actual             Expected              Error            RelativeError      AbsoluteTolerance
            _____    __________    ________________    _________________    ________________    _________________    _________________
        
             20        (5,4)       1.00000005321048    -1.00000010642496    2.00000015963544    -1.99999994678553          1e-06      
             29        (4,6)       1.00000005321248    -1.00000010642496    2.00000015963744    -1.99999994678753          1e-06      
    
    Actual Value:
       0.999999999917733                   0                   0  -0.000000707091158   1.000000760306419   1.000000760306419
                       0   1.000000000028756                   0  -1.000000053215261                   0  -1.000000053215261
                       0                   0   0.999999999917733  -1.000000760306419   1.000000760306419  -0.000000707091158
                       0                   0                   0   1.000000053212480                   0   1.000000053212480
                       0                   0                   0   1.000000053210480                   0  -1.000000053210480
    Expected Value:
       1.000000000000000                   0                   0                   0   1.000000106424960   1.000000000000000
                       0   1.000000000000000                   0  -1.000000106424960                   0  -1.000000000000000
                       0                   0   1.000000000000000  -1.000000000000000   1.000000000000000                   0
                       0                   0                   0   1.000000000000000                   0  -1.000000106424960
                       0                   0                   0  -1.000000106424960                   0  -1.000000000000000





<!-- Sent from Reviewable.io -->

2018-12-20 02:33 UTC, rleontie reviewed
let me edit the Matlab path to make sure I only have the current folder and I will fix any errors I get. Will report back in a bit

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU8SMIS6ROy-evuSMKN:bftfaxj)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 32 at r11](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8LNv-9h0Vmugr811X:-LU8SIVQAnDETfDcVNMZ:b-f185bv) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/d9fa3b88ee35653931a34f91a8fb93e4889284b7/computeRevoluteJointConstraints.m#L32)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It's in the spherical joint one too.
</blockquote></details>

so sorry about this. 


<!-- Sent from Reviewable.io -->

2018-12-20 02:44 UTC, rleontie commented
Everything should be running is only the TestcomputeRevoluteJacobianNum. and TestcomputeRevoluteJacobianDotV.m tests that are failing, but no runtime errors bugs on my side like the matrix dimensions one.





<!-- Sent from Reviewable.io -->

2018-12-20 02:59 UTC, edrumwri reviewed
Your (probably newer) version of Matlab might try to be doing something smarter than mine and figure you're really want to "repmat" it. But without that assumption, you're trying to do arithmetic on two differently sized matrices.

> Reviewed 2 of 2 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-:-LU8Y0uh0qRb4BMA37PS:b-4lm255)* status: all files reviewed, 2 unresolved discussions (waiting on @edrumwri and @rleontie)



<!-- Sent from Reviewable.io -->

2018-12-20 03:02 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: all files reviewed, 3 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 39 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8Yn7m8YzjEz5Li3RH:-LU8Yn7m8YzjEz5Li3RI:b-22zpeo) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/200b83b45e7b896c1304a1b196338ad72f2bd369/computeRevoluteJointConstraints.m#L39)):*
> ```objc
>     vjw = wRj * vj; 
> 
>     [v1iw, v2iw] = computeBasisFromAxis(viw);
> ```

I tried replacing these with ones that are computed only once and passed in and _then_ rotated to the global frame. That change fixed your problem. That's my mistake!


<!-- Sent from Reviewable.io -->

2018-12-20 03:14 UTC, rleontie commented
___
*[computeRevoluteJointConstraints.m, line 39 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8Yn7m8YzjEz5Li3RH:-LU8abDz-Pj7aZYHYxXq:b-m3hxm4) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/200b83b45e7b896c1304a1b196338ad72f2bd369/computeRevoluteJointConstraints.m#L39)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I tried replacing these with ones that are computed only once and passed in and _then_ rotated to the global frame. That change fixed your problem. That's my mistake!
</blockquote></details>

not sure what to do here. Are you saying to compute the basis from the local vector, and then rotate them to the global frame? 
[v1i, v2i] = computeBasisFromAxis(vi);
v1w = wRj * v1i;
v2w = wRj * v2i;


<!-- Sent from Reviewable.io -->

2018-12-20 03:48 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeRevoluteJointConstraints.m, line 39 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8Yn7m8YzjEz5Li3RH:-LU8ieMp96zmvP4_uIZr:byr4flj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/200b83b45e7b896c1304a1b196338ad72f2bd369/computeRevoluteJointConstraints.m#L39)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

not sure what to do here. Are you saying to compute the basis from the local vector, and then rotate them to the global frame? 
[v1i, v2i] = computeBasisFromAxis(vi);
v1w = wRj * v1i;
v2w = wRj * v2i;

</blockquote></details>

Right.


<!-- Sent from Reviewable.io -->

2018-12-20 14:16 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @edrumwri)

___
*[computeRevoluteJointConstraints.m, line 39 at r8](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU8Yn7m8YzjEz5Li3RH:-LUAy8uz238I7EaVbh5Q:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/200b83b45e7b896c1304a1b196338ad72f2bd369/computeRevoluteJointConstraints.m#L39)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Right.
</blockquote></details>

Done.
___
*[TestcomputeRevoluteJacobianDotV.m, line 21 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62u12C8mduu4X4inP:-LUAyIHV6ZbHZkFlgZPr:b-4yepp2) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianDotV.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Not able to determine until we fix the bug. Currently, this test is failing. 
</blockquote></details>

3e-6 is actually all I am able to get. There is a term here that has this error


<!-- Sent from Reviewable.io -->

2018-12-20 14:47 UTC, rleontie commented
Checkpoint. Maybe ready to merge? I am almost ready with the next pull request :)





<!-- Sent from Reviewable.io -->

2018-12-20 16:24 UTC, edrumwri approved these changes
> Reviewed 1 of 1 files at r14, 8 of 8 files at r15.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: all files reviewed, 1 unresolved discussion (waiting on @rleontie)

___
*[TestcomputeRevoluteJacobianDotV.m, line 21 at r6](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LU62u12C8mduu4X4inP:-LUBQMzaEhPKOx9QioqH:bs5n5d4) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/78311c574ca7842dfd8c0ce8429a5768d6cc9a74/TestcomputeRevoluteJacobianDotV.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

3e-6 is actually all I am able to get. There is a term here that has this error
</blockquote></details>

That is actually a bit concerning. I would have expected higher accuracy given that there is no numerical differentiation happening in this test.
___
*[computeRevoluteJacobianDotV.m, line 5 at r15](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5#-LUBQ3ztC2nvYwkaQwjF:-LUBQ3zu1IXhQnf-ZUIM:bee3zp5) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5460dcb69ced5a5a4dc8c839e66e1caf9a8f5d4f/computeRevoluteJacobianDotV.m#L5)):*
> ```objc
> %   Based on the formula:
> %   \dot{f}     = J * v, 
> %   \ddot{f}    = \dot{J} * v + J * \dot{v}, we than have
> ```

Nit than -> then


<!-- Sent from Reviewable.io -->

2018-12-20 17:55 UTC, rleontie commented
Should we merge, or do you want me to add the simulation files here?





<!-- Sent from Reviewable.io -->

2018-12-20 17:57 UTC, edrumwri approved these changes
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/5)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-20 17:58 UTC, merged