simulate revolute joint dynamics
edrumwri/revolute-joint-parameter-estimation pull request #6
Opened 2018-12-20 19:37 UTC by rleontie

2018-12-20 21:21 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @rleontie)

___
*[computeActingForces.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCUf8Z6zqQFjavp39w:-LUCUf8Z6zqQFjavp39x:bjxlqe9) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L1)):*
> ```objc
> function [F, M] = computeActingForces(mass, J, quat, w)
> ```

This function does more than simply compute forces- it also returns the generalized inertia matrix.
___
*[computeActingForces.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCUYck48aApthNHXKA:-LUCUYck48aApthNHXKB:b-cp1te6) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L3)):*
> ```objc
> function [F, M] = computeActingForces(mass, J, quat, w)
> % computeActingForces given the mass, inertia tensor J, orientation q,
> %   and angular velocity w returns the forces acting on a
> ```

Please note which frames J and w are to be expressed in.
___
*[computeActingForces.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCURm66Sfboq48h9gY:-LUCURm66Sfboq48h9gZ:b-72wtg2) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L7)):*
> ```objc
>  
>  g = 9.8;
>  R = qt2rot(quat);
> ```

Please label `R` using frame notation.


<!-- Sent from Reviewable.io -->

2018-12-20 21:51 UTC, edrumwri requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: all files reviewed, 18 unresolved discussions (waiting on @rleontie)

___
*[odeRevoluteF.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZAXP6pqvJpcFTTT_:-LUCZAXP6pqvJpcFTTTa:bgrskxt) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L1)):*
> ```objc
> function dydt = odeRevoluteF(init, mass, J, ui, vi, vj)
> ```

Currently only your `init` parameter is labeled. Please label all parameters.
___
*[odeRevoluteF.m, line 2 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZIenCRm00ooub7FG:-LUCZIeo11vwRmk9dV3d:bkf9vr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L2)):*
> ```objc
> function dydt = odeRevoluteF(init, mass, J, ui, vi, vj)
> % odeRevoluteF setups the dynamic system for the revolute joint as a
> ```

Nit: "setups" -> "sets up"
___
*[odeRevoluteF.m, line 2 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZS0-1UnQTV_6psOr:-LUCZS0-1UnQTV_6psOs:b-qrzp32) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L2)):*
> ```objc
> function dydt = odeRevoluteF(init, mass, J, ui, vi, vj)
> % odeRevoluteF setups the dynamic system for the revolute joint as a
> ```

No need to point out how the revolute joint is modeled.
___
*[odeRevoluteF.m, line 13 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZWRP7-o-Q5Ec92Ng:-LUCZWRP7-o-Q5Ec92Nh:by2cqyj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L13)):*
> ```objc
> 
>     
>     %extract the quaternion
> ```

Nit space after %
___
*[odeRevoluteF.m, line 17 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZa971FyykC0QBe-F:-LUCZa971FyykC0QBe-G:b-czblby) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L17)):*
> ```objc
>     % Angular velocity wx wy wz
>     angularVel = init(11:13);
>     % Velovity vector: containing linear velocity init(8:10) and angular velocity
> ```

Nit "Velovity"
___
*[odeRevoluteF.m, line 17 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZeoOE-nTxta2nCXJ:-LUCZeoOE-nTxta2nCXK:b-hslekp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L17)):*
> ```objc
>     % Angular velocity wx wy wz
>     angularVel = init(11:13);
>     % Velovity vector: containing linear velocity init(8:10) and angular velocity
> ```

This would read nicer if you named linear velocity as a variable too.
___
*[odeRevoluteF.m, line 29 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_8YA3Oklwtvq8rxU:-LUC_8YA3Oklwtvq8rxV:b-pqvj9b) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L29)):*
> ```objc
>     G = computeRevoluteJacobian(ui, vi, vj, pose);
>     GdotV = computeRevoluteJacobianDotVAnalytical(ui, vi, vj, quat, quatDot, velocity);
>     F = computeActingForces(mass, J, quat, angularVel);
> ```

Why are you calling this a second time?
___
*[odeRevoluteF.m, line 32 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_PfG6p-2S25SI-hc:-LUC_PfG6p-2S25SI-hd:bq382jm) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L32)):*
> ```objc
>     
>     % solving for x in the system Ax = b
>     % A = [ M -G'    x = [ \dot{v}      b = [ F
> ```

Please show the equations that you are attempting to solve, e.g., M\dot{v} - G'\lambda = F.
___
*[odeRevoluteF.m, line 33 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_IsI0KqF1HW2C0pm:-LUC_IsI0KqF1HW2C0pn:bvvzhcw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L33)):*
> ```objc
>     % solving for x in the system Ax = b
>     % A = [ M -G'    x = [ \dot{v}      b = [ F
>     %       G  0 ]         \dot(w)           -Gdot*V ]
> ```

I'd suggest referring to "v" as the generalized velocity (i.e., linear and angular velocity together).
___
*[odeRevoluteF.m, line 41 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_mfD9qDNNvAag9wH:-LUC_mfD9qDNNvAag9wI:b-hwv05x) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L41)):*
> ```objc
>     x = b\A;
>     %return the results
>       dydt = [init(8) % vx
> ```

I suggest using named variables here. In other words: dydt = [xdot; qdot; vdot];
___
*[simulate_revolute.m, line 5 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCa279CmkO1FaI9ufe:-LUCa279CmkO1FaI9uff:bl02exw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/simulate_revolute.m#L5)):*
> ```objc
> sphere_radius = 3;
> 
> % Moment of inertia tensor for a hallow sphere of radius r and mass m
> ```

"hallow" -> "hollow"
___
*[simulate_revolute.m, line 8 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCa4l4D1dYxwqT65oJ:-LUCa4l5461sR6KmiPjM:bm63hba) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/simulate_revolute.m#L8)):*
> ```objc
> J = getHollowSphereInertiaTensor(mass, sphere_radius);
> 
> ui = [-1; 0; 0];
> ```

Please label these variables in a comment.
___
*[simulate_revolute.m, line 22 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaFHpAlOrMSyecVky:-LUCaFHpAlOrMSyecVkz:b-cmeqrw) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/simulate_revolute.m#L22)):*
> ```objc
> tspan = [0;10];
> 
> [t,y3Drev] = ode45(@(t,y)odeRevoluteF(y, mass, J, ui, vi, vj),tspan,y0rev);
> ```

Nit spaces following commas
___
*[TestOdeRevoluteF.m, line 16 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaNYC5l5HYxd90Hjs:-LUCaNYC5l5HYxd90Hjt:b-ih7qrg) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L16)):*
> ```objc
>             vj = [0; 1; 0];
> 
>             % Moment of inertia tensor for a hallow sphere of radius r and mass m
> ```

hallow -> hollow
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUCaRpi0-ldQLxqhFwW:btqpl4c) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
> ```objc
>             
>             actSol = odeRevoluteF(init, mass, J, ui, vi, vj);
>             %not sure how to test this
> ```

You should test it under some easy-to-predict initial conditions. Pendulum is at rest, at 0 degrees and 90 degrees.


<!-- Sent from Reviewable.io -->

2018-12-20 23:31 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 0 of 4 files reviewed, 14 unresolved discussions (waiting on @edrumwri)

___
*[computeActingForces.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCUf8Z6zqQFjavp39w:-LUCjN-i5e63Qx5Rf6It:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This function does more than simply compute forces- it also returns the generalized inertia matrix.
</blockquote></details>

Done.
___
*[computeActingForces.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCUYck48aApthNHXKA:-LUCjMfTEz9jtaevv4C5:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please note which frames J and w are to be expressed in.
</blockquote></details>

Done.
___
*[computeActingForces.m, line 7 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCURm66Sfboq48h9gY:-LUCjNP72QDezgyBzcgS:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please label `R` using frame notation.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZAXP6pqvJpcFTTT_:-LUCxBbb7-rUvLi118ff:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Currently only your `init` parameter is labeled. Please label all parameters.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 2 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZS0-1UnQTV_6psOr:-LUCxDBX3D9DFOIy4X_K:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L2)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

No need to point out how the revolute joint is modeled.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 17 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCZeoOE-nTxta2nCXJ:-LUCkw460YxfMWTYnINu:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L17)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This would read nicer if you named linear velocity as a variable too.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 29 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_8YA3Oklwtvq8rxU:-LUCkzUE8U4lzxCi-ZQ1:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L29)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why are you calling this a second time?
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 32 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_PfG6p-2S25SI-hc:-LUCnqk58rO-1dbHRHUi:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L32)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please show the equations that you are attempting to solve, e.g., M\dot{v} - G'\lambda = F.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 33 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_IsI0KqF1HW2C0pm:-LUCnqGkDS8G6gZYjmIB:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L33)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'd suggest referring to "v" as the generalized velocity (i.e., linear and angular velocity together).
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 41 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUC_mfD9qDNNvAag9wH:-LUCnq1YC2q-Qy-vU8ZS:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/odeRevoluteF.m#L41)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I suggest using named variables here. In other words: dydt = [xdot; qdot; vdot];
</blockquote></details>

Done.
___
*[simulate_revolute.m, line 5 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCa279CmkO1FaI9ufe:-LUCxEsVEtWObP2bm_oJ:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/simulate_revolute.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"hallow" -> "hollow"
</blockquote></details>

Done.
___
*[simulate_revolute.m, line 8 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCa4l4D1dYxwqT65oJ:-LUCo55EC9H9zDR99udQ:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/simulate_revolute.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please label these variables in a comment.
</blockquote></details>

Done.
___
*[TestOdeRevoluteF.m, line 16 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaNYC5l5HYxd90Hjs:-LUCoQFUDHiaSeMzc77i:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L16)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

hallow -> hollow
</blockquote></details>

Done.
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUCwlswE7HjuWZsc73g:b-rvfcvf) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You should test it under some easy-to-predict initial conditions. Pendulum is at rest, at 0 degrees and 90 degrees.
</blockquote></details>

ok but to calculate this I still apply the same formulas... I am not sure how that is testing :)


<!-- Sent from Reviewable.io -->

2018-12-20 23:51 UTC, edrumwri requested changes
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 3 of 4 files reviewed, 12 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeActingForces.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCUf8Z6zqQFjavp39w:-LUD-S518stZbt6PwrP9:bqajme7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L1)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So isn't the function itself misnamed?
___
*[computeActingForces.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCUYck48aApthNHXKA:-LUD-IBoA74smL3DMQaj:b-nviu7n) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/computeActingForces.m#L3)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You're using a subscript but not actually saying which frames the quantities are defined in- you're relying upon the reader to make the connection that `wi` refers to the angular velocity in the body frame. 
___
*[computeActingForces.m, line 3 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-BIOC1RS3iQrkoP2:-LUD-BIOC1RS3iQrkoP3:bxo30v4) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/computeActingForces.m#L3)):*
> ```objc
> function [F, M] = computeActingForces(mass, Ji, quat, wi)
> % computeActingForces given the mass, inertia tensor Ji, orientation q,
> %   and angular velocity wi returns the forces acting on a
> ```

This should not be in the local frame.
___
*[odeRevoluteF.m, line 9 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-_9N7GNaIJUZllOX:-LUD-_9N7GNaIJUZllOY:b-4lm51m) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L9)):*
> ```objc
> %       linear velocity: init(8:10) vx vy vz
> %       angulat velocity: init(11:13) wx wy wz
> %   mass represent the mass at the joint
> ```

nit represent -> represents
___
*[odeRevoluteF.m, line 10 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-cBs4H-19cI1vTf_:-LUD-cBs4H-19cI1vTfa:b-xvaso6) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L10)):*
> ```objc
> %       angulat velocity: init(11:13) wx wy wz
> %   mass represent the mass at the joint
> %   Ji is the moment of inertia tensor for a hollow sphere of radius r and
> ```

which frame?
___
*[odeRevoluteF.m, line 12 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD07yZERnMcG9v2FqL:-LUD07yZERnMcG9v2FqM:brle9lg) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L12)):*
> ```objc
> %   Ji is the moment of inertia tensor for a hollow sphere of radius r and
> %   mass m.
> %   ui is a 3x1 vector from the center-of-mass of body i to the revolute 
> ```

It's no longer clear what is body i
___
*[odeRevoluteF.m, line 36 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-r5v6BdtK5hVuDm1:-LUD-r5v6BdtK5hVuDm2:b-nmyb8n) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L36)):*
> ```objc
>      
>     G = computeRevoluteJacobian(ui, vi, vj, pose);
>     GdotV = computeRevoluteJacobianDotVAnalytical(ui, vi, vj, quat, quatDot, velocity);
> ```

Here you are calling generalized velocity "V"; elsewhere you call it "vel".
___
*[simulate_revolute.m, line 7 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD037_6sVr0Z7uxVhQ:-LUD037_6sVr0Z7uxVhR:b8tvxlc) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/simulate_revolute.m#L7)):*
> ```objc
> % Moment of inertia tensor for a hollow sphere of radius r and mass m
> J = getHollowSphereInertiaTensor(mass, sphere_radius);
> %   ui is a 3x1 vector from the center-of-mass of body i to the revolute 
> ```

It's no longer clear what is "body i".
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUD0R-SDDf0ALInftvv:bpwuy30) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

ok but to calculate this I still apply the same formulas... I am not sure how that is testing :)
</blockquote></details>

You can ensure that the norm of vdot is 9.8m/s^2. I *think* that the acceleration of the bob will be straight downward, but this is my physical intuition (which is far form perfect).
___
*[TestOdeRevoluteF.m, line 25 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD0N636TbXJcg_aE9j:-LUD0N636TbXJcg_aE9k:bq8hexe) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/TestOdeRevoluteF.m#L25)):*
> ```objc
>         end 
>         
>         function testnoRotation(testCase)
> ```

Isn't this the same as the case above?


<!-- Sent from Reviewable.io -->

2018-12-21 01:22 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @edrumwri)

___
*[computeActingForces.m, line 3 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-BIOC1RS3iQrkoP2:-LUDFw-02Q90psics7Gl:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/computeActingForces.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This should not be in the local frame.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 10 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-cBs4H-19cI1vTf_:-LUDLZJoBUXBKw9CIMzZ:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

which frame?
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 12 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD07yZERnMcG9v2FqL:-LUDJ5H44MzA7T4kYC1d:bne6ags) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L12)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It's no longer clear what is body i
</blockquote></details>

would this work?
___
*[odeRevoluteF.m, line 36 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-r5v6BdtK5hVuDm1:-LUDIqDw4Nztx08WrlJE:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L36)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Here you are calling generalized velocity "V"; elsewhere you call it "vel".
</blockquote></details>

Done.
___
*[simulate_revolute.m, line 7 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD037_6sVr0Z7uxVhQ:-LUDJiQ7-C1-YRYCWJx2:b-xa2rau) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/simulate_revolute.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It's no longer clear what is "body i".
</blockquote></details>

link that is not fixed to the world?
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUDL8Kv6817Puh_Mcsp:bx7l5nd) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You can ensure that the norm of vdot is 9.8m/s^2. I *think* that the acceleration of the bob will be straight downward, but this is my physical intuition (which is far form perfect).
</blockquote></details>

maybe there is something wrong with my code... because that is definitely not the case :(
Actual Value:
       0.102040816326531
    Expected Value:
       9.800000000000001
___
*[TestOdeRevoluteF.m, line 25 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD0N636TbXJcg_aE9j:-LUDHl8J-1vL-FCOh3fS:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/TestOdeRevoluteF.m#L25)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Isn't this the same as the case above?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-21 17:55 UTC, edrumwri requested changes
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 3 of 4 files reviewed, 12 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[odeRevoluteF.m, line 12 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD07yZERnMcG9v2FqL:-LUGsoM_33PzKiUJfvT6:bun62sp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L12)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

would this work?
</blockquote></details>

I think you should just call it "the bob" and (immediately below) the "bob frame".
___
*[odeRevoluteF.m, line 36 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD-r5v6BdtK5hVuDm1:-LUGt7KjAQf6k-fYyF51:b-cs7gvg) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L36)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Except now you have "Vel" and "vel"...
___
*[odeRevoluteF.m, line 2 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsNqVDpKTg3wLLEoI:-LUGsNqVDpKTg3wLLEoJ:b15baj) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L2)):*
> ```objc
> function dydt = odeRevoluteF(init, mass, Ji, ui, vi, vj)
> % odeRevoluteF sets up the dynamic system for the revolute joint 
> ```

This isn't the dynamic system for the revolute joint. This is the ODE for a pendulum constrained in absolute coordinates.
___
*[odeRevoluteF.m, line 3 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsd9s67ew-a9WDj-K:-LUGsd9t6Ucy6thMEJLv:b-n448rs) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L3)):*
> ```objc
> function dydt = odeRevoluteF(init, mass, Ji, ui, vi, vj)
> % odeRevoluteF sets up the dynamic system for the revolute joint 
> % init is the initial conditions 13 x 1 vector containing:
> ```

These are no longer "initial conditions" but the state at which the derivative is to be computed.
___
*[odeRevoluteF.m, line 10 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsi4Q5xmWv_E97hBs:-LUGsi4R0eWkG0Zo1zQP:b-bl8yoo) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L10)):*
> ```objc
> %       angulat velocity: init(11:13) wx wy wz
> %   mass represents the mass at the joint
> %   Ji is the moment of inertia tensor (in the link i frame) for a hollow 
> ```

You want to call this the pendulum bob frame.
___
*[odeRevoluteF.m, line 15 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsyarEqA74v5dJTWz:-LUGsyarEqA74v5dJTX-:b-13gf04) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L15)):*
> ```objc
> %       joint location and expressed in the i frame (link i is not fixed to the world). 
> %   vi is a 3x1 unit vector that points along the axis of the revolute joint 
> %       expressed in the i frame (link i is not fixed to the world). 
> ```

I don't think it's necessary to point out that the bob is not affixed to the world. If it were, you wouldn't need an ODE for it!
___
*[simulate_revolute.m, line 7 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD037_6sVr0Z7uxVhQ:-LUGtBAP3hpB1WbEAquU:b-gltbhv) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/simulate_revolute.m#L7)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

link that is not fixed to the world?
</blockquote></details>

The bob.
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUGtGMyBTsMoCeHXm4l:b-l69y34) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

maybe there is something wrong with my code... because that is definitely not the case :(
Actual Value:
       0.102040816326531
    Expected Value:
       9.800000000000001

</blockquote></details>

Your initial conditions are wrong, your axes (vi, etc.) are wrong, and the plots don't display a circular motion (which is likely due to these problems). We now have some confident that the underlying code is sound. You should not be trying to merge code in until you are able to get the circular pendulum plot.
___
*[computeActingForcesAndInertia.m, line 1 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGSoXS4PSD9k2ulbB-:-LUGSoXS4PSD9k2ulbB0:b-uq0rdo) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/computeActingForcesAndInertia.m#L1)):*
> ```objc
> function [F, M] = computeActingForcesAndInertia(mass, Ji, quat, angularVel)
> ```

This isn't a (3x3) inertia matrix. It's a "generalized inertia matrix" or "generalized mass matrix".
___
*[computeActingForcesAndInertia.m, line 4 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGTSncCUj-srUjTSP6:-LUGTSncCUj-srUjTSP7:b-5c6s8s) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/computeActingForcesAndInertia.m#L4)):*
> ```objc
> % computeActingForcesAndInertia given the mass, inertia tensor Ji, orientation quat,
> %   and angular velocity angularVel returns the forces acting on a
> %   revolute joint: mass matrix and generalized inertia matrix M and forces F.
> ```

These aren't the forces acting on a revolute joint, but the forces acting on a body. Jb (I don't see a reason to call it body i in this file) is the inertia matrix expressed and measured in the body frame. w0 is the angular velocity of the body expressed in the global frame. The forces 
___
*[computeActingForcesAndInertia.m, line 5 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGTKOz8xcjODoTtv2y:-LUGTKOz8xcjODoTtv2z:b-2vhete) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/computeActingForcesAndInertia.m#L5)):*
> ```objc
> %   and angular velocity angularVel returns the forces acting on a
> %   revolute joint: mass matrix and generalized inertia matrix M and forces F.
> %   Inertia tensor Ji is the i frame (not fixed to the world)
> ```

"is the i frame" -> "is in the body b frame"


<!-- Sent from Reviewable.io -->

2018-12-21 20:10 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @edrumwri)

___
*[computeActingForcesAndInertia.m, line 1 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGSoXS4PSD9k2ulbB-:-LUHIey06usQEXNxIArI:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/computeActingForcesAndInertia.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This isn't a (3x3) inertia matrix. It's a "generalized inertia matrix" or "generalized mass matrix".
</blockquote></details>

Done.
___
*[computeActingForcesAndInertia.m, line 4 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGTSncCUj-srUjTSP6:-LUHIgX3CZhhbK94qkxt:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/computeActingForcesAndInertia.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

These aren't the forces acting on a revolute joint, but the forces acting on a body. Jb (I don't see a reason to call it body i in this file) is the inertia matrix expressed and measured in the body frame. w0 is the angular velocity of the body expressed in the global frame. The forces 
</blockquote></details>

Done.
___
*[computeActingForcesAndInertia.m, line 5 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGTKOz8xcjODoTtv2y:-LUHIhKg77zQFUyjPd9x:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/computeActingForcesAndInertia.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"is the i frame" -> "is in the body b frame"
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 12 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD07yZERnMcG9v2FqL:-LUHNv6OBTUcZuevpHa3:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/odeRevoluteF.m#L12)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I think you should just call it "the bob" and (immediately below) the "bob frame".
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 2 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsNqVDpKTg3wLLEoI:-LUHNq1F5QV9fWzWIJqj:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L2)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This isn't the dynamic system for the revolute joint. This is the ODE for a pendulum constrained in absolute coordinates.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 3 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsd9s67ew-a9WDj-K:-LUHNr8k3OzSVPYe3LEt:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

These are no longer "initial conditions" but the state at which the derivative is to be computed.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 10 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsi4Q5xmWv_E97hBs:-LUHNtr9BWaWYsRL6S_a:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You want to call this the pendulum bob frame.
</blockquote></details>

Done.
___
*[odeRevoluteF.m, line 15 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUGsyarEqA74v5dJTWz:-LUHKcm03XDVoP7vZSxo:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/fa28a9699ca7f23812bbd13b894e1043c1b24f02/odeRevoluteF.m#L15)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't think it's necessary to point out that the bob is not affixed to the world. If it were, you wouldn't need an ODE for it!
</blockquote></details>

Done.
___
*[simulate_revolute.m, line 7 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUD037_6sVr0Z7uxVhQ:-LUHLo-g9WcF1lGoS5i6:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/bfc6795f12b0b6acc65618645b488f349892d98c/simulate_revolute.m#L7)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The bob.
</blockquote></details>

Done.
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUHMwst9dLwsPSqfqcH:b-3pjb5v) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Your initial conditions are wrong, your axes (vi, etc.) are wrong, and the plots don't display a circular motion (which is likely due to these problems). We now have some confident that the underlying code is sound. You should not be trying to merge code in until you are able to get the circular pendulum plot.
</blockquote></details>

How are the axes pointing? I was assuming y is pointing downward, mainly because of the forces matrix that has -mg in the y component


<!-- Sent from Reviewable.io -->

2018-12-23 17:37 UTC, edrumwri requested changes
It seems like you're rushing through this code- I'm seeing a lot more spelling and grammatical issues than usual. Are you checking your work before hitting "publish" in Reviewable?

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-:-LUR6S_h3P4InpmL6KU5:b8g3w0n)* status: all files reviewed, 8 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[computeActingForcesAndGeneralizedInertia.m, line 3 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR640G4kOkkzqMZrxI:-LUR640HBmi0fNtPqRjq:bbpr6sa) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/computeActingForcesAndGeneralizedInertia.m#L3)):*
> ```objc
> function [F, M] = computeActingForcesAndGeneralizedInertia(mass, Jb, quat, angularVel)
> % computeActingForcesAndGeneralizedInertia returns generalized inertia matrix M 
> %   and forces acting forces F for body b.
> ```

"forces acting forces"?
___
*[computeActingForcesAndGeneralizedInertia.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR66q_3C_41HE9krb0:-LUR66q_3C_41HE9krb1:b-kgt5cp) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/computeActingForcesAndGeneralizedInertia.m#L4)):*
> ```objc
> % computeActingForcesAndGeneralizedInertia returns generalized inertia matrix M 
> %   and forces acting forces F for body b.
> %   mass is the bass of body b.
> ```

sp: bass
___
*[computeActingForcesAndGeneralizedInertia.m, line 6 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR6AEA-3nNJCHYZQhS:-LUR6AEA-3nNJCHYZQhT:b-m6whix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/computeActingForcesAndGeneralizedInertia.m#L6)):*
> ```objc
> %   mass is the bass of body b.
> %   Jb is the inertia tensor of the body b expressed in the body b frame. 
> %   quat is the orientation of the body b.
> ```

FYI Suggest "orientation of the body b relative to the global frame"
___
*[odePendulumF.m, line 8 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR6eRCAjd4Sm1Jzglo:-LUR6eRCAjd4Sm1Jzglp:b-qazw90) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/odePendulumF.m#L8)):*
> ```objc
> %   orientation: init(4:7) as quaternion qw qx qy qz
> %   velocity: as 
> %       linear velocity: init(8:10) vx vy vz
> ```

please specify frames for velocities
___
*[odePendulumF.m, line 9 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR6PZr-V1omxHAZyVU:-LUR6PZr-V1omxHAZyVV:b-9vslpg) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/odePendulumF.m#L9)):*
> ```objc
> %   velocity: as 
> %       linear velocity: init(8:10) vx vy vz
> %       angulat velocity: init(11:13) wx wy wz
> ```

sp: angulat
___
*[simulatePendulum.m, line 24 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR78_dAazwF8HlvfaO:-LUR78_dAazwF8HlvfaP:b-htyaep) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/simulatePendulum.m#L24)):*
> ```objc
> %       linear velocity: y0rev(8:10) vx vy vz
> %       angulat velocity: y0rev(11:13) wx wy wz
> y0rev = [0; 0; 0; 1; 0; 0; 0; 0; 0; 0; 0; 0; 0];
> ```

It would be a good idea before simulating to verify that the revolute joint constraints evaluate to zero.
___
*[TestODEPendulumF.m, line 18 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR7wtU-Kt_mIlZAtjQ:-LUR7wtU-Kt_mIlZAtjR:bv7h3rr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/TestODEPendulumF.m#L18)):*
> ```objc
>             % Moment of inertia tensor for a hollow sphere of radius r and mass m
>             J = getHollowSphereInertiaTensor(mass, sphere_radius);
>             init = [0; 0; 0; 1; 0; 0; 0; 0; 0; 0; 0; 0; 0];
> ```

As with my comment in simulatePendulum.m, you should verify that your constraints evaluate to zero at the initial conditions.
___
*[TestOdeRevoluteF.m, line 21 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUCaRpi0-ldQLxqhFwV:-LUR7NbKDX91scTqxAa6:b-srdack) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/f6b707eba06d47382f9e231116ded2dc8e4252ff/TestOdeRevoluteF.m#L21)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

How are the axes pointing? I was assuming y is pointing downward, mainly because of the forces matrix that has -mg in the y component
</blockquote></details>

Your axes vectors in simulatePendulum.m are what I expected. They're not the same vectors here. 


<!-- Sent from Reviewable.io -->

2018-12-24 17:23 UTC, rleontie commented
___
*[simulatePendulum.m, line 24 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR78_dAazwF8HlvfaO:-LUWE0O83RIKjMEOHr--:b-fvfpm7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/simulatePendulum.m#L24)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It would be a good idea before simulating to verify that the revolute joint constraints evaluate to zero.
</blockquote></details>

are you saying that the revolute constraints form the Jacobian calculations? if so, if they don't evaluate to zeros, does that mean the Jacobian is still wrong? Otherwise the cross product it is zeros!


<!-- Sent from Reviewable.io -->

2018-12-25 22:40 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: all files reviewed, 8 unresolved discussions (waiting on @edrumwri and @rleontie)

___
*[simulatePendulum.m, line 24 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR78_dAazwF8HlvfaO:-LUbWTWx07CbsNoUgqPH:b-sivhh9) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/simulatePendulum.m#L24)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

are you saying that the revolute constraints form the Jacobian calculations? if so, if they don't evaluate to zeros, does that mean the Jacobian is still wrong? Otherwise the cross product it is zeros!
</blockquote></details>

That's not what I'm saying. I'm saying that if your initial conditions are valid, the constraint equations will evaluate to zero.


<!-- Sent from Reviewable.io -->

2018-12-26 01:36 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @edrumwri)

___
*[computeActingForcesAndGeneralizedInertia.m, line 3 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR640G4kOkkzqMZrxI:-LUW89n99MnUhw6YX6Jx:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/computeActingForcesAndGeneralizedInertia.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"forces acting forces"?
</blockquote></details>

Done.
___
*[computeActingForcesAndGeneralizedInertia.m, line 4 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR66q_3C_41HE9krb0:-LUW89WHBPmbVchMLXOB:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/computeActingForcesAndGeneralizedInertia.m#L4)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

sp: bass
</blockquote></details>

Done.
___
*[computeActingForcesAndGeneralizedInertia.m, line 6 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR6AEA-3nNJCHYZQhS:-LUW87W53HGsl529lDvE:bb6un1j) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/computeActingForcesAndGeneralizedInertia.m#L6)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI Suggest "orientation of the body b relative to the global frame"
</blockquote></details>

Done
___
*[odePendulumF.m, line 8 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR6eRCAjd4Sm1Jzglo:-LUW83TJBDYFi7nm2gR3:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/odePendulumF.m#L8)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

please specify frames for velocities
</blockquote></details>

Done.
___
*[odePendulumF.m, line 9 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR6PZr-V1omxHAZyVU:-LUW84gH1ggUyDOD0unN:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/odePendulumF.m#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

sp: angulat
</blockquote></details>

Done.
___
*[simulatePendulum.m, line 24 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR78_dAazwF8HlvfaO:-LUc1aPvAeEJ4cmvFbmT:b-pjcsbf) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/simulatePendulum.m#L24)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

That's not what I'm saying. I'm saying that if your initial conditions are valid, the constraint equations will evaluate to zero.
</blockquote></details>

Ok Done. I see my mistake here, I did that in trying to debug :)
___
*[TestODEPendulumF.m, line 18 at r4](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LUR7wtU-Kt_mIlZAtjQ:-LUc7Mt01aRHfRdTXrtH:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/a1fc6db894372c00577e6915fea257d6f0de210a/TestODEPendulumF.m#L18)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

As with my comment in simulatePendulum.m, you should verify that your constraints evaluate to zero at the initial conditions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-26 17:13 UTC, edrumwri reviewed
> Reviewed 4 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 4 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-01-10 22:22 UTC, edrumwri requested changes
> Reviewed 1 of 6 files at r5, 4 of 7 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: all files reviewed, 8 unresolved discussions (waiting on @rleontie)

___
*[TestValidStartState.m, line 10 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqHiP8rAgh9kD6H28:-LVtqHiP8rAgh9kD6H29:b-3gi44t) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestValidStartState.m#L10)):*
> ```objc
>         function testValid(testCase)
>           % validStartState with good inital conditions.
>           pose = [1 0 0 1 0 0 0]';
> ```

I recommend breaking the pose up like you did elsewhere:
    xcom = [1 0 0]';
    q = [1 0 0 0]';
    pose = [xcom; q];
___
*[TestValidStartState.m, line 11 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqPlgEEofUOR4LmdT:-LVtqPlgEEofUOR4LmdU:bsd8gvn) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestValidStartState.m#L11)):*
> ```objc
>           % validStartState with good inital conditions.
>           pose = [1 0 0 1 0 0 0]';
>           ub = [-1; 0; 0];
> ```

Please label ub, vb, and vj.
___
*[TestValidStartState.m, line 16 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqSiG4fbknE4l2LGr:-LVtqSiG4fbknE4l2LGs:bl7gao7) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestValidStartState.m#L16)):*
> ```objc
>           actSol = validStartState(pose, ub, vb, vj);
>           expSol = 1;
>           testCase.verifyEqual(actSol, expSol, 'AbsTol', sqrt(eps));
> ```

This is a much bigger tolerance than you used elsewhere.
___
*[validStartState.m, line 1 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqdat-DLiMc0bQNdw:-LVtqdat-DLiMc0bQNdx:b-tytg4u) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/validStartState.m#L1)):*
> ```objc
> function boolean = validStartState(pose, ub, vb, vj, tol)
> ```

"boolean" is a type, not a variable name. Please think of an appropriate name for this variable.
___
*[validStartState.m, line 13 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqkqS2PNPpwxMHjm4:-LVtqkqS2PNPpwxMHjm5:bym7y5g) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/validStartState.m#L13)):*
> ```objc
> %   vj is a 3x1 unit vector that points along the axis of the revolute joint 
> %       expressed in the j frame (fixed to the world).
> %   tol is the optional scalar tolerance. If not present tolerance is 0. 
> ```

You never want to make tolerance zero. I just suggest making this parameter non-optional (easiest).
___
*[odePendulumF.m, line 47 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVt2W4m8Fxsuz81-T_r:-LVt2W4n3VqTh9Qjv9qv:bsjd0n2) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/odePendulumF.m#L47)):*
> ```objc
>     b = [F; -GdotVel];
>     
>     x = A\b; % use pinv(A) * b if radius is 0.
> ```

Nit there is no notion of a "radius" in this file. I suggest removing this comment.
___
*[TestODEPendulumF.m, line 12 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtpXdgDDnWX0ZIefEC:-LVtpXdgDDnWX0ZIefED:b-dy3xsy) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestODEPendulumF.m#L12)):*
> ```objc
>         
>         function testPendulumFromHorizontal(testCase)
>             % The pendulum is horizontal (90 with the vertical axis). 
> ```

I don't actually know what you mean by "90 with the vertical axis". I'd suggest just replacing the parenthetical with "(the bob lies on +x)"
___
*[TestODEPendulumF.m, line 16 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtptYf1mdrpdl6_xpz:-LVtptYg937H9u83-JGp:bde9rng) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestODEPendulumF.m#L16)):*
> ```objc
>             sphere_radius = 0;
>             ub = [-1; 0; 0];
>             vb = [0; 0; 1];
> ```

Please add comments to remind us what "ub", "vb", and "vj" are, and what frame they're expressed in.


<!-- Sent from Reviewable.io -->

2019-01-11 01:53 UTC, rleontie reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @edrumwri)

___
*[TestValidStartState.m, line 10 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqHiP8rAgh9kD6H28:-LVuHqaP4wg_di07hunT:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestValidStartState.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I recommend breaking the pose up like you did elsewhere:
    xcom = [1 0 0]';
    q = [1 0 0 0]';
    pose = [xcom; q];
</blockquote></details>

Done.
___
*[TestValidStartState.m, line 11 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqPlgEEofUOR4LmdT:-LVuHqJg0hzYvj-ZJVAF:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestValidStartState.m#L11)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please label ub, vb, and vj.
</blockquote></details>

Done.
___
*[TestValidStartState.m, line 16 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqSiG4fbknE4l2LGr:-LVu_ESD0gXxMQoD1ku7:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestValidStartState.m#L16)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This is a much bigger tolerance than you used elsewhere.
</blockquote></details>

Done.
___
*[validStartState.m, line 1 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqdat-DLiMc0bQNdw:-LVu_WVqBdDwTptu5heI:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/validStartState.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"boolean" is a type, not a variable name. Please think of an appropriate name for this variable.
</blockquote></details>

Done.
___
*[validStartState.m, line 13 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtqkqS2PNPpwxMHjm4:-LVu_XNs9BxicZ4bOhI5:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/validStartState.m#L13)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You never want to make tolerance zero. I just suggest making this parameter non-optional (easiest).
</blockquote></details>

Done.
___
*[TestODEPendulumF.m, line 12 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtpXdgDDnWX0ZIefEC:-LVuGnHA-V0I0JgJq9gE:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestODEPendulumF.m#L12)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't actually know what you mean by "90 with the vertical axis". I'd suggest just replacing the parenthetical with "(the bob lies on +x)"
</blockquote></details>

Done.
___
*[TestODEPendulumF.m, line 16 at r7](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6#-LVtptYf1mdrpdl6_xpz:-LVu_98I8krvsl5o-NVF:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/5b0a4edec6b7b9be76b0fd8ff7a8685bdf3dc8cd/TestODEPendulumF.m#L16)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please add comments to remind us what "ub", "vb", and "vj" are, and what frame they're expressed in.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-01-11 17:27 UTC, edrumwri approved these changes
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-01-11 17:27 UTC, merged